### ISSUE TITLE
Error during creation of Kathara machine: iptables not found.

### ISSUE THREAD

**Issue by DavideTomasella** [KatharaFramework/Kathara#101]
**Describe the bug/how to reproduce**
When you try to start a new laboratory or a single machine with Ethernet connection (`kathara vstart -n pc1 --eth 0:A`) in Katharà 2.2.3 on Windows 10 using Docker Desktop this error appairs:
```
===================== Starting Machine ======================
←[?25lDeploying links...CRITICAL - 500 Server Error: Internal Server Error ("NetworkDriver.CreateNetwork: unable to enable rule:  (iptables failed: iptables --wait -A FORWARD -i kt-3783a907fe2d -o kt-3783a907fe2d -j ACCEPT: iptables v1.8.2 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain FORWARD
 (exit status 4))")
```
In the machine (with no network configured) the output of `iptables --list` is:
 ```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```
while `iptables --version` returns `iptables v1.6.0`.
The containers created in Docker are both kathara/quagga and kathara/base.

I saw that the NetworkPlugin support both iptables v1.6 and v1.8 but there isn't an option to choose which one to used.
I have both plugins installed as `docker plugin ls` shows:
```
ID                  NAME                        DESCRIPTION              ENABLED
92e7926897b8        kathara/katharanp:buster    Kathara Network Plugin   true
577b6e94a36b        kathara/katharanp:stretch   Kathara Network Plugin   true
```
but, if I try to disable `kathara/katharanp:buster`, creating a new machine re-enable it.

Maybe I'm missing some configs?

<details>
<summary>"check" Command Output</summary>
*       Current Manager is: Docker (Kathara)
*       Manager version is: 19.03.13
*       Python version is: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
*       Kathara version is: 2.2.3
*       Trying to run `Hello World` container...
←[?25lDeploying links...
Deploying machines... |################################| 1/1
←[?25h* Container run successfully.
Deleting machines... |################################| 2/2
←[?25h←[?25lDeleting links...
←[?25h
</details>

**Comment by lorenzo93** [comment]
Hi @DavideTomasella ,

The problem is related to the usage of Docker with WLS2 backend instead of Hyper-V backend.
I've created a patch, in the afternoon we'll release a new version with this patch.

Thanks for pointing out the issue.

**Comment by lorenzo93** [comment]
I've released the new version.
In `kathara settings` there is a new flag that has to MANUALLY be enabled when you are executing Kathará with WLS2.

Please tell me if it solves the problem.

**Comment by DavideTomasella** [comment]
Thanks @lorenzo93. Now it seems to work properly.

**Comment by MaryTB** [comment]
It works fine for me too....

**Comment by MOHAMED5465** [comment]
Bonjour 
je travaille avec windows x64
je travaille avec la dernière version de docker 
kathara semble ne pas marcher , en effet la commande   kathara vstart -n pc1 --eth 0:A   retourne l erreur suivante :  CRITICAL (FileNotFoundError) [WinError 2] Le fichier spécifié est introuvable

De meme lorsque je suis sur un répertoire ou j ai un fichier conf , ca me donne une erreur pareil lors de la commande kathara lstart , l erreur : CRITICAL (FileNotFoundError) [WinError 2] Le fichier spécifié est introuvable

J arrive pas a trouver l erreur , et j ai besoin que ca marche pour les tp de mon ecole.
merci
