### ISSUE TITLE
Error while installing on windows

### ISSUE THREAD

**Issue by lazypanda19** [KatharaFramework/Kathara#102]
Hello, i tried to run "kathara ltest" but there is an error like this

500 Server Error: Internal Server Error ("NetworkDriver.CreateNetwork: unable to enable rule:  (iptables failed: iptables --wait -A FORWARD -i kt-64f6f532058c -o kt-64f6f532058c -j ACCEPT: iptables v1.8.2 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain FORWARD
 (exit status 4))")
![Capture](https://user-images.githubusercontent.com/72733558/95725785-4bbf5e00-0ca2-11eb-81ca-cd18dd632d42.PNG)

**Comment by Skazza94** [comment]
Hi @lazypanda19,
please refer to issue #101 to fix this problem
