### ISSUE TITLE
WinError 2

### ISSUE THREAD

**Issue by lazypanda19** [KatharaFramework/Kathara#103]
Hello, i cant run the vstart syntax, there is an error like this
![unknown](https://user-images.githubusercontent.com/72733558/95883958-ba391480-0da5-11eb-96df-255b34b45332.png)

**Comment by tcaiazzi** [comment]
Hi @lazypanda19, 
Kathará on windows is not compatible with CMD, so you have to use the PowerShell. 
Moreover, you started the CMD with Administrator Privileges and it is not recommended and tested.

So try to use a PowerShell with NO Administrator Privileges and let us know.

Thanks

**Comment by lazypanda19** [comment]
Hi @tcaiazzi ,
Thanks for the response, I will try using powershell when i have a time to test it, I will tell you if the issue is fixed by this
Thank you

**Comment by Skazza94** [comment]
Since the last reply was 10 days ago I'm considering the issue as solved or no longer relevant.

If you need further support, you can open another issue.

Thanks!
