### ISSUE TITLE
Docker.Core.HttpBadResponseException: {"status":"error","message":"exit status 2"}

### ISSUE THREAD

**Issue by dariucc** [KatharaFramework/Kathara#105]
I installed docker following the guide.
When I use it for the first time it works without any problem, but on the first restart it crashes and it reports the attached error.
I tried to google it and I tried this solution https://github.com/docker/for-win/issues/7110 but I couldn't solve the problem.
Did anyone face my same problem and solved it?

  - Windows Version:  Version:OS 2004 Build 19041.572 but not running neither on a previous version (windows 1909)
  - Docker Desktop Version: latest version 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

  1. Install Docker
  2. Create a container with katharà 
  3. Enable wls2 in katharà settings
  4. Works
  5. After restarting Docker, it crashes

  The error:

Docker.Core.HttpBadResponseException:
{"status":"error","message":"exit status 2"}

   in Docker.Core.Logging.HttpClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\HttpClientExceptionInterceptor.cs:riga 26
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:riga 36
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Docker.Core.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:riga 16
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Docker.ApiServices.LifecycleClient.<DockerStartAsync>d__10.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\LifecycleClient.cs:riga 122
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Docker.LinuxkitDaemonStartup.<StartAsync>d__5.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\LinuxkitDaemonStartup.cs:riga 30
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:riga 160
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:riga 29
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:riga 67
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   in Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:riga 92

**Comment by honoraryp** [comment]
I have the same issue, I’ve tried installing different packets on docker, like mango, and it works just fine even after a docker restart, so I think the problem is the latest version of katharà.

**Comment by honoraryp** [comment]
Do you, @dariucc, by any chance have a laptop with a ryzen 4000 series processor, because i have one and is the only pc that has the problem you described, the others with intel processors work just fine.

**Comment by dariucc** [comment]
hello, my main PC has an i7 8550u CPU and I also tested another PC with an i7 7700hq but it had the same problem. I was wondering if it could depend on the installed version of Windows 10.
Which version do you have?

**Comment by lorenzo93** [comment]
Hi,

we investigated the problem and seems to have found a solution.
Tomorrow we'll double check and then release an upgrade.

Thanks for pointing out the bug, we'll keep you posted

**Comment by honoraryp** [comment]
> hello, my main PC has an i7 8550u CPU and I also tested another PC with an i7 7700hq but it had the same problem. I was wondering if it could depend on the installed version of Windows 10.
> Which version do you have?

On my laptop i have the latest release which is the 2004, but i didn't work even before the update, on the others i have older version, i thin it is the 1909

**Comment by honoraryp** [comment]
> Hi,
> 
> we investigated the problem and seems to have found a solution.
> Tomorrow we'll double check and then release an upgrade.
> 
> Thanks for pointing out the bug, we'll keep you posted

Thank you so much to you for acknowledging the problem and responding i so little time

**Comment by Skazza94** [comment]
Hi @honoraryp and @dariucc,
we're still investigating (the problem seems bigger than expected).

We'll keep you updated.

**Comment by honoraryp** [comment]
I don't know if it helps, but apparently the problem appears when you enable the wls2 option in the kathara settings, at least this is the problem i encountered.
Hoping to hear from you soon

**Comment by atrahtafreshi** [comment]
hello, I have the same problem too.

**Comment by Skazza94** [comment]
Hi everyone,
digging into this problem we found that it is a bug related to Docker Desktop using WSL2 (it is still unstable). 
We opened an issue: https://github.com/docker/for-win/issues/9282, please up-vote it so it has more visibility.

In the meantime, you can switch to Hyper-V backend that works without any problem.

**Comment by atrahtafreshi** [comment]
> Hi everyone,
> digging into this problem we found that it is a bug related to Docker Desktop using WSL2 (it is still unstable).
> We opened an issue: [docker/for-win#9282](https://github.com/docker/for-win/issues/9282), please up-vote it so it has more visibility.
> 
> In the meantime, you can switch to Hyper-V backend that works without any problem.

hi , would you please tell me how can I switch to Hyper-v ? (I am using windows 10 )

**Comment by Skazza94** [comment]
> 
> hi , would you please tell me how can I switch to Hyper-v ? (I am using windows 10 )

From Docker Desktop dashboard, click on Settings (the cog icon) and untick "Use the WSL 2 based engine", then click "Apply & Restart".

**Comment by tcaiazzi** [comment]
Hi all! 
Docker released a new stable version of Docker Desktop (2.5.0.0, https://docs.docker.com/docker-for-windows/release-notes/) that fix this issue. 
We tested the new version and it seems to work well. It is only needed to upgrade  Docker Desktop. 

Thanks.
