### ISSUE TITLE
Dependencies errors

### ISSUE THREAD

**Issue by edoardottt** [KatharaFramework/Kathara#106]
**Describe the bug**
Installation process on Linux gives me these dep errors... Maybe this problem has been already solved.

**To Reproduce**
1. I followed exactly your Linux installation guide

**Expected behavior**
Katharà installed.

```
The following packages have unmet dependencies:
 kathara : Depends: libffi6 (>= 3.0.4) which is a virtual package and is not provided by any avilable package

           Depends: libreadline7 (>= 7.0~beta) which is a virtual package and is not provided by any available package
```

**Comment by Skazza94** [comment]
Hi @edoardottt,
seems that you have an old version of Ubuntu/Debian?

Which one do you have?

**Comment by edoardottt** [comment]
Sorry, I downloaded a Lubuntu ISO and I've figured out now it's Groovy 20.10.
With Focal Fossa it works fine. 
Thanks for the quick answer
