### ISSUE TITLE
lstart not working using Docker Toolbox on Windows 8.1 - 64 bit

### ISSUE THREAD

**Issue by Akelatnx** [KatharaFramework/Kathara#109]
Hi to everybody.

I have an old pc so I had to install a deprecated version of Docker Toolbox but Kathara seemed to work anyway: I was able to create and start single machines, but if I use the command lstart I get the error in the attached image.

How can I solve this? I need it to work for my class... :-(

Thanks in advance!

![2020-11-04_005302](https://user-images.githubusercontent.com/74187103/98539071-02a3ff00-228c-11eb-9a1f-7dc85ac3dc3e.jpg)

**Comment by tcaiazzi** [comment]
Hi @Akelatnx, 

what version of Docker and Windows are you using?

Thanks.

**Comment by Akelatnx** [comment]
Hi!

I'm using Windows 8.1 - 64 bit and Docker Toolbox 19.03.1

**Comment by Skazza94** [comment]
Hi @Akelatnx, 
could you please try the following?

Type `kathara settings`, choose `(**Windows only**) Enable WLS2 Support` option and choose `Yes` to enable it.
Try again to start a lab and tell us if it's working.

**WARNING**: Keep in mind that the WSL2 flag will be removed in the next Kathará release, so you can't update it to newer versions (>2.2.4) if you don't update your OS to Win10 and the latest Docker Desktop release.

Thanks,
Mariano.

**Comment by Akelatnx** [comment]
It worked! :-)

Thank you so very much!!! :-)
