### ISSUE TITLE
[WinError 2] Impossibile trovare il file specificato

### ISSUE THREAD

**Issue by GiuliaMaragno** [KatharaFramework/Kathara#110]
Hello, I can't run the vstart and the lstart syntax.
Powershell shows me an ERROR like this:
![Errore](https://user-images.githubusercontent.com/66382585/98921043-21470780-24d1-11eb-9a4b-5c55a2097c35.PNG)

**Comment by Skazza94** [comment]
Hi @GiuliaMaragno,
seems like Docker Desktop is not running. Before using Kathara you should ensure that Docker Desktop is running on your system (you can doing so by checking the tray icons).

If the problem persists, we'll further investigate.

Also, I suggest you to update to the latest Kathará version ([3.0.1](https://github.com/KatharaFramework/Kathara/releases/tag/3.0.1)) that we released yesterday!

Thanks,
Mariano.

**Comment by GiuliaMaragno** [comment]
Hi @Skazzino, 
Docker Desktop is currently running.
I’ve updated the version this morning but it doesn't work.
![image](https://user-images.githubusercontent.com/66382585/98932464-a5a08700-24df-11eb-9898-af8c6bab1e8c.png)

Waiting for your kind feedback, 

Best regards,
Giulia.

**Comment by Skazza94** [comment]
Hi @GiuliaMaragno,
thanks for you feedback.

To better understand what's happening, activate the debug logging as follows:
- Type `kathara settings`
- Go into `Choose logging level to be used` and choose `DEBUG`
- Exit from settings
- Start a machine with `kathara vstart ...`

A detailed log will be outputted, please paste it here.

Thanks,
Mariano.

**Comment by GiuliaMaragno** [comment]
Hi @Skazzino, 
Here is the output: 
![image](https://user-images.githubusercontent.com/66382585/98934491-74758600-24e2-11eb-9315-a9fd13f5a914.png)

**Comment by Skazza94** [comment]
Hi @GiuliaMaragno,
the device creation is correct (so it is started), but there's a problem with terminal opening.

First of all, from the output above seems like Kathara is not at version 3.0.1, so please update it (overwriting the current installation in "C:\Program Files\Kathara"). Second, maybe you opened Powershell as administrator. Please use Powershell without administration privileges.

Thanks, 
Mariano.

**Comment by GiuliaMaragno** [comment]
Hi @Skazzino, 
I'm currently using the PowerShell without administration privileges, and I just updated Katharà version, but it still doesn't work. 
The output is the following:
![image](https://user-images.githubusercontent.com/66382585/98938052-9c1b1d00-24e7-11eb-8bb8-d6eb66bcccda.png)
If I use administration privileges, the output is this:
![image](https://user-images.githubusercontent.com/66382585/98938264-ea302080-24e7-11eb-8ca9-620764a87cce.png)

**Comment by Skazza94** [comment]
Hi @GiuliaMaragno,
we released another version of Kathara (3.0.3). Here we added few options that can help debugging this issue.

First of all, update Kathara and run `kathara check` and paste the output.

After that:
- Type `kathara settings`
- Go into `Choose logging level to be used` and choose `EXCEPTION`
- Exit from settings
- Start a machine with `kathara vstart ...` and upload the output (stack trace will be printed after the error)

**Comment by GiuliaMaragno** [comment]
Hi @Skazzino, 

- this is the output of "katharà check" after the update:

![image](https://user-images.githubusercontent.com/66382585/98968311-ced80c00-250d-11eb-8045-408afdb1c553.png)

- this is the output after "kathara vstart -n pc1"

![image](https://user-images.githubusercontent.com/66382585/98968763-6178ab00-250e-11eb-8095-14037c34f9e7.png)

Thanks, 
Giulia.

**Comment by Skazza94** [comment]
Hi @GiuliaMaragno,
with the stack trace I can understand that it is a problem related to PowerShell.

Please in PowerShell type `$env:path` and report the output. 

Thanks.

**Comment by GiuliaMaragno** [comment]
Hi @Skazzino, 
that's the output:
![image](https://user-images.githubusercontent.com/66382585/98969795-81f53500-250f-11eb-8f36-4dff1fb6a6a2.png)
Thanks, 
Giulia

**Comment by Skazza94** [comment]
Hi @GiuliaMaragno,
seems like it not a problem related to Kathara. The PowerShell path is a little strange (as you can see there's a `;c:\dig` after the powershell path).

Remove the double quotes around PowerShell and dig path.

Thanks,
Mariano

**Comment by GiuliaMaragno** [comment]
Hi @Skazzino, 
now it works correctly!!
Thanks for your time, 
Giulia.

**Comment by Skazza94** [comment]
Hi @GiuliaMaragno,
no problem! We're here to help you! :)

I'm closing this issue.
