### ISSUE TITLE
Add proper linux support (not debian-based)

### ISSUE THREAD

**Issue by 174n** [KatharaFramework/Kathara#111]
My feature request would be to add support for linux distros other than debian-based (Arch, Fedora for instance).

The instructions are strictly debian-based (although it says linux there): https://github.com/KatharaFramework/Kathara/wiki/Linux

**Comment by Skazza94** [comment]
Hi @Rundik,
other users already requested this feature. 

We're working to build binary packages for Yum and Pacman. We'll keep you updated.

Thanks.

**Comment by 174n** [comment]
Is there any temporary solution to run it on fedora?

**Comment by tcaiazzi** [comment]
Hi @Rundik,
we're working to build binary packages for Yum and Pacman. However we are still not ready to release the binaries. 
For now, you can compile it (for Fedora) from the `linux-builds` branch, entering the `scripts/Linux-Rpm` directory and running `make`.  This will build a binary rpm file in the `Output` directory. 
 
Otherwhise you can use Kathará directly from the source code: 
`python3 kathara.py <command>` . 

Let us know if you have problems! 

Thanks.

**Comment by Skazza94** [comment]
Hi @Rundik,
[release 3.0.6](https://github.com/KatharaFramework/Kathara/releases/tag/3.0.6) adds binaries for Yum and Pacman. For now we're releasing them as binary files, but we'll create a custom Yum repo and upload the pkg on AUR really soon.

I'm closing this issue, if you have any other problem, don't hesitate to open a new one.

Thanks,
Mariano.
