### ISSUE TITLE
Lab not working

### ISSUE THREAD

**Issue by la187937** [KatharaFramework/Kathara#119]
Hello, could you please help me?
I try to launch the basic lab but Kathara doesn't start-it. 
Kathara check works, Kathara vstart works but the lab not
![probleme kathara](https://user-images.githubusercontent.com/76121277/102381415-78a52f80-3fc9-11eb-84fd-203d792d89ee.PNG)

Thank you!

**Comment by tcaiazzi** [comment]
Hi @la187937, 

it seems that docker is not running or that you don't have internet connection on the host. 
So, please, try to start docker and check that you are connected to the internet. 

N.B. : in general, the internet connection is not needed, but you have to download and install the kathara network plugin first. 

Let us know if you have problems!

Thanks, 
Tommaso.

**Comment by la187937** [comment]
Thank you for your prompt response! 
Docker is started. How can i check that I'm connected to the internet? (My personal computer is connected to the wifi!)

Thanks

**Comment by Skazza94** [comment]
Hi @la187937,
to check if you're connected to the internet, you can try to ping google.com. From a terminal, type `ping google.com` and check if it returns a proper response. Also, just for information, you can check if Docker is running typing `docker ps` from a terminal.

Some additional information to dig into the issue: are you using a Powershell or the classic `cmd`? Can you please attach the output of the `kathara check` command?

Thanks,
Mariano.

**Comment by la187937** [comment]
Hi Mariano
Thank you for you help! I saw  tha I'm connected to the internet with the ping.
However , I lauch the kathara check! there is an error !
Here a screenshot
![Probleme kathara1](https://user-images.githubusercontent.com/76121277/102416973-1cf39a00-3ffb-11eb-89be-eca139ec770b.PNG)

thank you.

**Comment by Skazza94** [comment]
Hi @la187937,
are you using PowerShell as CLI?

**Comment by la187937** [comment]
Hi Mariano!
no I am using cmd

**Comment by Skazza94** [comment]
Hi @la187937,
as already reported in other issues (like #103), Kathará on Windows only works on Powershell (without admin privileges).

So please, try to use it and tell us if you still encounter any problem.

Thanks, 
Mariano.

**Comment by la187937** [comment]
Hi Mariano,
I try to launch kathara with powershell but it doesn't work !
and there aren't any created machines on docker!
However the kathara check works! 
![Probleme powershell](https://user-images.githubusercontent.com/76121277/102477336-83f56b00-405c-11eb-828c-3f34fed4b0f2.JPG)
![Probleme powershell1](https://user-images.githubusercontent.com/76121277/102477345-88218880-405c-11eb-9463-faffd7bcbb5c.JPG)
![Probleme powershell2](https://user-images.githubusercontent.com/76121277/102477358-8bb50f80-405c-11eb-9618-6a95d8e7eea6.JPG)
![docker](https://user-images.githubusercontent.com/76121277/102477373-8f489680-405c-11eb-9345-755c88028443.JPG)

**Comment by Skazza94** [comment]
Hi @la187937,
okay, now Kathará works but there's a problem with Docker Desktop. Are you using version 3.0.0? 

P.S. Remember to run a `kathara wipe` before relaunching the lab!

**Comment by la187937** [comment]
Hi Mariano, 

THANK YOU VERY MUCH!!!
Everything works!!

Have a good day ! bye bye !

**Comment by Skazza94** [comment]
Hi @la187937,
glad to hear that everything works fine! 😄 

I'm closing this issue, if you have any other problem don't hesitate to open another one.

Mariano.
