### ISSUE TITLE
AUR package: missing dependency chrpath

### ISSUE THREAD

**Issue by fam4r** [KatharaFramework/Kathara#124]
**Describe the bug**
Hi, it seems that the AUR package fails during the build operation due to a missing dependency, to be precise the `chrpath` package.

**To Reproduce**
```bash
$ yay -Syu kathara
```

**Expected behavior**
The package builds succesfully.

**Screenshots**
Appending the very last lines of the build log (I can provide the full log if needed):

```
Nuitka-Scons:INFO: Running gcc -o module.pyasn1_modules.rfc2459.o -c -std=c11 -fvisibility=hidden -fwrapv -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -fcompare-debug-second -O3 -pipe -D_FORTIFY_SOURCE=2 -D_NUITKA_STANDALONE -D__NUITKA_NO_ASSERT__ -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=164 -D_NUITKA_EXE -I/usr/include/python3.9 -I. -I/home/famar/.local/lib/python3.9/site-packages/nuitka/build/include -I/home/famar/.local/lib/python3.9/site-packages/nuitka/build/static_src module.pyasn1_modules.rfc2459.c took 284.05 seconds
Nuitka-Scons:WARNING: You are not using ccache.
FATAL: Error, needs 'chrpath' on your system, due to 'RPATH' settings in used shared 
libraries that need to be removed.
==> ERROR: A failure occurred in build().
    Aborting...
error making: kathara
```

Installing the `chrpath` package makes the build succeed.

PS: since the AUR package is now available, could you please also update the wiki (https://github.com/KatharaFramework/Kathara/wiki/Linux#arch-based)?

Thank you

**Comment by Skazza94** [comment]
Hi @fam4r, 
I added the `chrpath` dependency in the PKGBUILD.
I also updated the Wiki to include the steps for AUR.

Thanks for the issue,
Mariano.
