### ISSUE TITLE
vdump command

### ISSUE THREAD

**Issue by nisevi** [KatharaFramework/Kathara#126]
Hi there, not sure if this is an issue or I'm just failing to find in the documentation the equivalent to `vdump` that we used to have when installing [net-kit](https://netkit-ng.github.io/umldump.html). Is that the case? Do we no longer have a command like `vdump`?

Thank you for the great work you do :rocket:

**Comment by Skazza94** [comment]
Hi @nisevi,
the `vdump` command is not part of the original NetKit commands (it has been added in one of the new forks). Hence, there's no support for it in Kathará.

However, if you want to dump packets from a single device interface, you can use `tcpdump` inside that device.
You can write an output file in `/shared` folder (inside the device) and you'll find the dumps inside the `shared` folder of the lab directory.

If you need further help, don't hesitate to ask!

Thanks,
Mariano.

**Comment by nisevi** [comment]
Hey @Skazza94!! thank you for your quick answer, and sorry for my delay! Sure thing I will try what you mention :rocket: 

Closing this one in the meanwhile :robot:
