### ISSUE TITLE
Connect Kathara Lab to host machine

### ISSUE THREAD

**Issue by kwaku104** [KatharaFramework/Kathara#129]
Is there a way to connect a kathara lab to a host machine via an "external interface" or a network interface? 

I'm trying to set up the lab in such a way that I can ssh into a Kathara device from my host machine. 

A work around for my use case will be to use "kathara-exec" to execute commands in a kathara device from my host machine but it doesn't seem to work for commands that include flags.

![Screenshot 2021-07-15 at 12 55 55 PM](https://user-images.githubusercontent.com/37820793/125784481-54f851cb-a576-43ed-9dfb-c42357b76198.png)

**Comment by tcaiazzi** [comment]
Hi @kwaku104, 

you have to put `--` before the command: 

```bash 
kathara exec router1 -- vtysh -c "show ip bgpg"
```
A double-dash (`--`) in a shell command signals the end of options and disables further option processing.
You can find other information [here](https://www.baeldung.com/linux/double-dash-in-shell-commands).

Cheers, 
Tommaso
