### ISSUE TITLE
Move linux hidden files (with a leading .)  into Dockers

### ISSUE THREAD

**Issue by francozamp2** [KatharaFramework/Kathara#134]
I'm unsure if this is a bug or rather a feature request. The problem is that Linux hidden files included in the tree filesystem of a lab machine are not copied during the laboratory deployment.

I traced back this issue to the file https://github.com/KatharaFramework/Kathara/blob/master/src/Resources/model/Machine.py in which in line 127 _glob_ is used to collect all files and put them into an archive (which is then extracted into the running Docker instance). 

According to this post, https://stackoverflow.com/questions/49047402/python-3-6-glob-include-hidden-files-and-folders _glob_ ignores hidden files (i.e., starting by .)  and this is a problem for labs needing to include .htaccess files for apache2.

While this can be arranged with a copy in the startup it would be nice to have this fixed (p.s. apparently also hidden files in the special folder /hostlab are not available)

Thanks!!!!

F.

**To Reproduce**
1. create a folder for a host into a lab: mkdir pc1
2. create a hidden file in such folder: touch pc1/.test
3. run: kathara lstart
4. verify with ls -a that the file is not inside the Docker

**Comment by Skazza94** [comment]
Hi @francozamp2,
thanks for the issue.
This is a problem that surely requires a fix. I'll address that and merge it in the next release.

Thanks!

**Comment by Skazza94** [comment]
Hi @francozamp2,
I fixed this issue, the fix is now in the [`develop` branch](https://github.com/KatharaFramework/Kathara/commit/928eb642ba30352f27ffb4852359be12a0671aab#diff-2ed00e6c405c74537da2690be48dc1b7d9066d5f2f9fe31a3a8124db1991bf3e).

It'll be available really soon in the new release.

Thanks for the bug report!
