### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Kien221** [KatharaFramework/Kathara#136]
Hi everyone, I'm need the help of everyone about issues :
-bash: /install: No such file or directory
when input $NETKIT_HOME/install  to install Kathara. Although I edited "bash environment variable" is:
export NETKIT_HOME=~/KatharaMMT/bin
export PATH=$PATH:$NETKIT_HOME
export MANPATH=:$NETKIT_HOME/man
Thank you so much!!

**Comment by Skazza94** [comment]
Hi @Kien221,
I don't know where you found such commands, but they are related to an old version of Kathará (<2.0) which is not supported anymore.

I suggest you to update to the latest version of Kathará. You can find the installation instructions for Linux [here](https://github.com/KatharaFramework/Kathara/wiki/Linux).

Mariano.

**Comment by Kien221** [comment]
> Hi @Kien221,
> I don't know where you found such commands, but they are related to an old version of Kathará (<2.0) which is not supported anymore.
> 
> I suggest you to update to the latest version of Kathará. You can find the installation instructions for Linux [here](https://github.com/KatharaFramework/Kathara/wiki/Linux).
> 
> Mariano.

so thank you so much was support for me , I have successfully installed kathara.
