### ISSUE TITLE
How to run Katharà on Apple M1

### ISSUE THREAD

**Issue by tcaiazzi** [KatharaFramework/Kathara#140]
**Describe the bug**
Kathará does not work correctly on Apple devices with M1 processor. 

**To Reproduce**
1. Install Kathará on a Apple device with M1 processor.
2. Run a device or a scenario with at least 1 collision domain. 
3. Obtain the following error: 
![image](https://user-images.githubusercontent.com/26346836/138699922-420010b5-5982-423f-b2d1-0184d066d1c4.png)

**Expected behavior**
Kathará should work correctly.

**Comment by tcaiazzi** [comment]
Unfortunately, an official release for M1 processors is still under development. 
However, the Docker images and the Network Plugin are ready, so waiting for an official release, it is still possible to use Kathará.

**Solution**
You have to perform the following steps: 
1.  Open a terminal.
2. If present, uninstall the old Docker Network Plugin for x86:  
    - `docker plugin rm -f kathara/katharanp:latest`.
3. Clone the Kathará Network Plugin repository:
    - `git clone https://github.com/KatharaFramework/NetworkPlugin.git`
4. Enter the Network Plugin directory and open the Makefile with a text editor.
5. Change line 38 of the Makefile:
   - From: `docker plugin create ${PLUGIN_NAME}:$* ./plugin-src/`
   - To: `docker plugin create ${PLUGIN_NAME}:latest ./plugin-src/`
6. From the terminal, run the Makefile with:
    - `make all_arm64`
7. Now, if you have Kathará already installed then it should work. Otherwise, install it ([Installation Guide](https://github.com/KatharaFramework/Kathara/wiki/Macos)).

**Comment by oliverjamarie** [comment]
Thank you! I've been having to work with slow Virtual Machines for 2 months!

**Comment by tcaiazzi** [comment]
Finally we officially release a Kathará version (3.3.0) supporting Apple M1 processors! Check the [release page](https://github.com/KatharaFramework/Kathara/releases/tag/3.3.0).
