### ISSUE TITLE
`kathara exec` hangs indefinitely when running ping command

### ISSUE THREAD

**Issue by giossa94** [KatharaFramework/Kathara#143]
**Describe the bug**
`kathara exec` hangs indefinitely when running a specific ping command into a device belonging to a lab. I reproduced the issue with a lab generated with [VFTGen](https://github.com/KatharaFramework/VFTGen), but seems to be related to Kathara and not an issue with VFTGen.

**To Reproduce**
1. Clone [VFTGen](https://github.com/KatharaFramework/VFTGen) repo
2. Run VFTGen with default config: `python3 vftgen.py`
3. Go to the generated lab directory and run `kathara lstart`
4. When the previous step is finished, run `kathara exec server_2_1_1 -- ping 200.0.0.2` (or any ping between devices of the lab) 

**Actual behavior**
The `kathara exec` command hangs indefinitely and doesn't display the ping output.

**Expected behavior**
Ping output is displayed.

**Extra comments**
- If I run `kathara connect` and run the ping command from the container, it works normally. 
- If I run `docker exec -it <container_name> ping 200.0.0.2` it works fine too.

<details>
<summary>"check" Command Output</summary>

```
Current Manager is: Docker (Kathara)
Manager version is: 20.10.11
Python version is: 3.9.7 (default, Sep 10 2021, 00:03:59) - [GCC 7.5.0]
Kathara version is: 3.2.0
Operating System version is: Linux-5.4.0-91-generic-x86_64
```

</details>

Any ideas on how I can solve this issue? Thank you!

**Comment by tcaiazzi** [comment]
Hi @giossa94, 

We fixed it! Check the develop branch and commit https://github.com/KatharaFramework/Kathara/commit/0df94296b248863107956bce3c7891184311d526. 

We will merge the fix in the next release!

Many thanks for your help!

Tommaso.

**Comment by giossa94** [comment]
Thank you for the quick fix!

**Comment by conraddang** [comment]
Hi, somehow i encountered the same problem, while it should be fixed, right? What should i do so that the ping output gets displayed? I’d really appreciate any help with this!

**Comment by tcaiazzi** [comment]
Dear @conraddang, 

Thank you for reaching out!

I just tested it on my PC, and everything is working perfectly on my end. 

![image](https://github.com/user-attachments/assets/9afc4853-c2ce-475e-978a-34c6f43fe61b)

Are you sure you're pinging a reachable IP? If not, the command might get stuck waiting for a timeout.

To assist you further, I’ll need some additional information:
1. Could you provide a step-by-step guide on how to reproduce the issue?
2. Which OS are you using?
3. What version of Kathará are you running?

Thanks!
