### ISSUE TITLE
External Link Errors

### ISSUE THREAD

**Issue by jimmad123** [KatharaFramework/Kathara#144]
**Describe the bug**
When attempting to add an externally-facing collision domain to a lab using the `lab.ext` file, errors are thrown. This is not the case in older Kathara versions and the behaviour has only been noticed in version `3.2.0`. There were also issues with getting older versions, such as `3.1.0`, installed for testing (building from source did not work as expected - not the purpose of this issue, though).

**To Reproduce**
1. Set up  a lab including a `lab.ext` file, configured as per the man pages.
2. Run the lab using `sudo kathara lstart`
3. See error

In our most basic test, a single-machine lab was configured with only one interface that was externally facing. There were other tests using more emulated devices/interfaces but the same issues were encountered. This has been found on multiple host machines across different physical interfaces.

**Expected behavior**
As with past Kathara versions, it is expected that the lab runs as normal and the externally-facing interface can be interacted with like other interfaces in the lab.

**Screenshots**
![image](https://user-images.githubusercontent.com/44371017/145234191-c90f3063-ac59-4145-9b21-230e5ac92148.png)
(there is no further output after the "Deploying collision domains" line and it returns to prompt without the lab starting, I have just excluded this from the screenshot)

<details>
<summary>"check" Command Output</summary>
*	Current Manager is: Docker (Kathara)</br>
*	Manager version is: 20.10.11</br>
*	Python version is: 3.8.10 (default, Jun  2 2021, 10:49:15) - [GCC 9.4.0]</br>
*	Kathara version is: 3.2.0</br>
*	Operating System version is: Linux-5.4.0-91-generic-x86_64</br>
*	Trying to run `Hello World` container...</br>
Deploying devices... |####################################################| 1/1</br>
*	Container run successfully.</br>
Deleting devices... |#####################################################| 1/1</br>
</details>

**Comment by Skazza94** [comment]
Hi @jimmad123,
thanks for the issue. In 3.2 version we switched to Python3.9, so maybe we forgot to update the dependency.
We'll address it as soon as possible and include a patch in the next release. 

Sorry for the inconvenience.
Mariano.

**Comment by Skazza94** [comment]
Hi @jimmad123,
we found that starting from pyroute2 0.6.1 they changed the organization of the package, hence Nuitka/PyInstaller (that we use to provide a binary) do not correctly import all the submodules.
Hence, we rolledback to pyroute2 0.5.9 waiting for a fix.

The rollback will be included in the next release (very soon).
