### ISSUE TITLE
Full Kathará install via pip

### ISSUE THREAD

**Issue by nopid** [KatharaFramework/Kathara#145]
Currently, Kathará is distributed in two different ways:
 1. as a binary package for different OS and architectures distributed on https://www.kathara.org;
 2. as a Python API distributed on PyPi : https://pypi.org/project/kathara/.

Both share the same source base hosted on this github repository. It is my understanding that the PyPi version is the whole Kathara source excepted [src/kathara.py](https://github.com/KatharaFramework/Kathara/blob/master/src/kathara.py) and  [src/Kathara/cli](https://github.com/KatharaFramework/Kathara/tree/master/src/Kathara/cli).

I would be a nice feature for people using the Python API to be able to have a single install.

Is there a reason not to distribute [src/kathara.py](https://github.com/KatharaFramework/Kathara/blob/master/src/kathara.py) and  [src/Kathara/cli](https://github.com/KatharaFramework/Kathara/tree/master/src/Kathara/cli) with the library? Some more depencies?

Having [src/kathara.py](https://github.com/KatharaFramework/Kathara/blob/master/src/kathara.py) as a main function inside the `kathara` package would further allow us to use kathara as `python3 -m kathara`.

One reason for me to ask is that the binary packages induce a noticeable overhead when launching kathará commands compared to using `kathara.py` directly.

_originaly discussed in https://github.com/KatharaFramework/Kathara/issues/131#issuecomment-993595851_

**Comment by tcaiazzi** [comment]
Hi @nopid, 
We added the cli to the PyPI package. 

Now you can run CLI Kathará command using `python3 -m kathara`.

Let us know if everything works fine! 

Thanks and Bye! 🚀

Tommaso

**Comment by nopid** [comment]
Hi @tcaiazzi,

That was fast ! 🚀

Thanks!

**Comment by nopid** [comment]
Hi @tcaiazzi,

It seems to work very well (I started a few vstart machines).
One little thing to fix:  `kathara -v` reports 3.3.0 instead of 3.3.1

**Comment by nopid** [comment]
Hi @tcaiazzi,

It worked under MacOS by under Linux there is one subtle thing to fix: connection is handled by https://github.com/KatharaFramework/Kathara/blob/3439b04ece541870d13b94a1f964e9b195417314/src/Kathara/model/Machine.py#L286

Which is implemented here:
https://github.com/KatharaFramework/Kathara/blob/3439b04ece541870d13b94a1f964e9b195417314/src/Kathara/utils.py#L65-L76

Under Linux the `kathara.py` file while be run without interpreter (as it should start by a sheband). However this will fail here because this file is not executable when installed by pip.

If we try to fix `utils.get_executable_path`, one might also want to change from `python` or `python3` to something like `sys.executable` as Kathará might be executed from inside a virtual env.

**Comment by Skazza94** [comment]
Hi @nopid,
I just pushed another version on PyPI (3.3.2) with the `sys.executable` fix. It seems to work. 

Thanks again!
