### ISSUE TITLE
Issues when parsing lab.dep with comment or blank lines

### ISSUE THREAD

**Issue by maurom** [KatharaFramework/Kathara#146]
Hi, first of all thanks for your work on this highly useful project.

I would like to point out some small issues with the lab.dep parser, for example:

- If the first line of a lab.dep is a comment, then the lab hangs when starting.
  E.g. on `kathara-lab_arp` with the following `lab.dep`

      # hi world
      pc1: r1
      pc2: r2 pc3

    I get

      INFO - ======================= Starting Lab ========================

    and then nothing else.

- The second issue is that dependencies are ignored after a blank line on the `lab.dep` file.
  E.g., the same lab with the following `lab.dep` starts (or might start) pc1, pc2 and pc3 before the required machines.

      r2: r1

      pc3: r2
      pc2: pc3
      pc1: pc2

It might be related to a missing readline() on the following condition of the parsing loop:

https://github.com/KatharaFramework/Kathara/blob/acd30ec399c3e69936952cf1bacf00e76ed916a8/src/Kathara/parser/netkit/DepParser.py#L45-L52

**Comment by Skazza94** [comment]
Hi @maurom,
thanks for your issue.

You're right, there was the bug you reported in the `DepParser` class. I've fixed it and pushed in the `fix-lab-dep` branch.

I'll merge it in the next Kathará release.

Happy hacking,
Mariano.

**Comment by maurom** [comment]
Works great! Thanks for fixing it so quickly!
