### ISSUE TITLE
Device Deployment Error/Problem

### ISSUE THREAD

**Issue by slasom** [KatharaFramework/Kathara#147]
I am using Kathara for network emulation in Docker containers with Android mobile images ([Docker Android](https://github.com/budtmo/docker-android)). 

I have a problem, when I try to deploy a high number of containers, Kathara is not able to deploy them, when it reaches the tenth container, the next ones are deployed very slowly which is not viable.

I find it strange because if I try to deploy the containers through Docker I deploy them without any problem, as I use quite powerful AWS instances (c5.metal or similar) for the virtualization of Android devices (they support more than 100 virtual devices at the same time).
What do you think could be the problem?

**Comment by lorenzo93** [comment]
Hi @slasom,
We never tried Kathará with an Android image.
However, we used Kathará on a cheap laptop with more than 30 devices and runs smoothly.

To understand if you are dealing with low resources or, if the problem is Kathará related or, if the problem is about the Android image, can you try to run a network scenario with the same topology (links and number of devices) using one of the Kathará's provided images?

Otherwise, if you can, send us your network scenario we'll test it ourselves.

Just for my curiosity, if you have a use case you want to share about using Android images, we'll be more than happy to hear it and add it to the [Community Labs](https://github.com/KatharaFramework/Kathara-Labs/wiki/Community-Labs).

**Comment by slasom** [comment]
Thank you very much for the quick response. 

I have tried some of the example images in the repository and there is no problem. So I don't know where the problem could be. The strange thing is that if I deploy them with Docker I can launch as many as I want. So I don't know if Kathara has any resource limitations or similar.

I have left a repository with the lab I am testing. Note that the image (since it uses the same one for all devices in this case) is quite heavy and resource-intensive.

https://github.com/slasom/Example-Kathara-Docker-Android

Each container is limited to 1.5 cpus and 3Gb of memory and requires 6Gb storage per container and there are 25 of them (I test on a c5.metal instance of AWS). Also, you have to have KVM virtualization for the virtual mobile devices to work, but if you don't, it may not matter, as long as Kathara launches the containers.....

And regarding the use case, OF COURSE! I'm currently integrating Kathara into a framework that allows to deployment of heterogeneous scenarios with virtual mobile devices. If I get it working properly, I'll be happy to explain a use case.

**Comment by lorenzo93** [comment]
> So I don't know if Kathara has any resource limitations or similar.

No, Kathará has no limitations in the current version (3.3.0).

> I have left a repository with the lab I am testing. Note that the image (since it uses the same one for all devices in this case) is quite heavy and resource-intensive.

I've tested your lab both on a Windows machine and on a Linux machine (both bare metal, 16GB of RAM, 4c-8t CPU). In both cases the entire lab starts in about 20-40 seconds but we do not have KVM enabled.
My idea is that the problem lies in your environment.

To further debug your situation, can you try to change the logging level and share with us the starting log?
You can change the logging level by launching command `kathara settings`, than going to `Choose logging level to be used` and select the `DEBUG` level. With this settings, when you start a lab, Kathará will be VERY verbose and it is possible to understand in which step it slows down.

**Comment by slasom** [comment]
Here it is, the only message that appears as a failure in each container is "DEBUG - failure: decodable_as_unicode: False" although it still deploys (up to at least the 10th container).



ubuntu@ip-172-31-38-230:~/kathara$ sudo kathara lstart -d ./lab --privileged
DEBUG - Machine architecture is `x86_64`.
WARNING - Running devices with privileged capabilities, terminals won't open!
INFO - ======================= Starting Lab ========================
DEBUG - `router` interfaces are [(0, Link(A, []))].
DEBUG - `device1` interfaces are [(0, Link(A, []))].
DEBUG - `device2` interfaces are [(0, Link(A, []))].
DEBUG - `device3` interfaces are [(0, Link(A, []))].
DEBUG - `device4` interfaces are [(0, Link(A, []))].
DEBUG - `device5` interfaces are [(0, Link(A, []))].
DEBUG - `device6` interfaces are [(0, Link(A, []))].
DEBUG - `device7` interfaces are [(0, Link(A, []))].
DEBUG - `device8` interfaces are [(0, Link(A, []))].
DEBUG - `device9` interfaces are [(0, Link(A, []))].
DEBUG - `device10` interfaces are [(0, Link(A, []))].
DEBUG - `device11` interfaces are [(0, Link(A, []))].
DEBUG - `device12` interfaces are [(0, Link(A, []))].
DEBUG - `device13` interfaces are [(0, Link(A, []))].
DEBUG - `device14` interfaces are [(0, Link(A, []))].
DEBUG - `device15` interfaces are [(0, Link(A, []))].
DEBUG - `device16` interfaces are [(0, Link(A, []))].
DEBUG - `device17` interfaces are [(0, Link(A, []))].
DEBUG - `device18` interfaces are [(0, Link(A, []))].
DEBUG - `device19` interfaces are [(0, Link(A, []))].
DEBUG - `device20` interfaces are [(0, Link(A, []))].
DEBUG - `device21` interfaces are [(0, Link(A, []))].
DEBUG - `device22` interfaces are [(0, Link(A, []))].
DEBUG - `device23` interfaces are [(0, Link(A, []))].
DEBUG - `device24` interfaces are [(0, Link(A, []))].
DEBUG - `device25` interfaces are [(0, Link(A, []))].
INFO -
Name: kathara-PERSES
Description: A kathara network emulating docker deployment
Author(s): PERSES-ORG

INFO - =============================================================
DEBUG - Raising privileges to UID=0 and GID=119...
DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
DEBUG - No config file found
DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
DEBUG - No config file found
DEBUG - http://localhost:None "GET /version HTTP/1.1" 200 798
DEBUG - Checking plugin `kathara/katharanp:amd64`...
DEBUG - http://localhost:None "GET /v1.41/plugins/kathara/katharanp:amd64/json H                                                      TTP/1.1" 200 None
DEBUG - http://localhost:None "GET /v1.41/_ping HTTP/1.1" 200 2
DEBUG - Dropping privileges to UID=0 and GID=0...
DEBUG - Raising privileges to UID=0 and GID=119...
DEBUG - http://localhost:None "GET /v1.41/networks?filters=%7B%22label%22%3A+%5B                                                      %22app%3Dkathara%22%5D%2C+%22name%22%3A+%5B%22kathara_ubuntu-rggnnirbwhynneti9hi                                                      sw_A%22%5D%7D HTTP/1.1" 200 3
DEBUG - http://localhost:None "POST /v1.41/networks/create HTTP/1.1" 201 87
DEBUG - http://localhost:None "GET /v1.41/networks/f1b7d40b354089db1ad0e7905f718                                                      09004632b9d1c7139e13acda420239ad137 HTTP/1.1" 200 562
DEBUG - wrapping excepthook
Deploying collision domains... |##########################################| 1/1
DEBUG - http://localhost:None "GET /v1.41/networks?filters=%7B%22name%22%3A+%5B%                                                      22bridge%22%5D%7D HTTP/1.1" 200 721
DEBUG - http://localhost:None "GET /v1.41/images/kathara/quagga/json HTTP/1.1" 2                                                      00 None
DEBUG - Checking updates for kathara/quagga...
DEBUG - http://localhost:None "GET /v1.41/images/kathara/quagga/json HTTP/1.1" 2                                                      00 None
DEBUG - Looking for auth config
DEBUG - No auth config in memory - loading from filesystem
DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
DEBUG - No config file found
DEBUG - Looking for auth entry for 'docker.io'
DEBUG - No entry found
DEBUG - No auth config found
DEBUG - http://localhost:None "GET /v1.41/distribution/kathara/quagga/json HTTP/                                                      1.1" 200 273
DEBUG - http://localhost:None "GET /v1.41/images/spilabuex/android9:gs6/json HTT                                                      P/1.1" 200 None
DEBUG - Checking updates for spilabuex/android9:gs6...
DEBUG - http://localhost:None "GET /v1.41/images/spilabuex/android9:gs6/json HTT                                                      P/1.1" 200 None
DEBUG - Looking for auth config
DEBUG - No auth config in memory - loading from filesystem
DEBUG - Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
DEBUG - No config file found
DEBUG - Looking for auth entry for 'docker.io'
DEBUG - No entry found
DEBUG - No auth config found
DEBUG - http://localhost:None "GET /v1.41/distribution/spilabuex/android9:gs6/js                                                      on HTTP/1.1" 200 231
DEBUG - Creating device `router`...
DEBUG - http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&                                                      trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22app%3Dkathara%22%2C+%22user%3Dubuntu                                                      -rggnnirbwhynneti9hisw%22%2C+%22lab_hash%3DIc4jpIN2IiiYvWa211oIOg%22%2C+%22name%                                                      3Drouter%22%5D%7D HTTP/1.1" 200 3
DEBUG - http://localhost:None "POST /v1.41/containers/create?name=kathara_ubuntu                                                      -rggnnirbwhynneti9hisw_router_Ic4jpIN2IiiYvWa211oIOg HTTP/1.1" 201 88
DEBUG - http://localhost:None "GET /v1.41/containers/028da56e375f70211be4c4a9c9c                                                      a87220f2418bc3e1aefae3509c64dc9a43d81/json HTTP/1.1" 200 None
DEBUG - is_binary: '/home/ubuntu/kathara/lab/router.startup'
DEBUG - nontext_ratio1: 0.0
DEBUG - nontext_ratio2: 1.0
DEBUG - is_likely_binary: False
DEBUG - detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language':                                                       ''}
DEBUG - failure: decodable_as_unicode: False
DEBUG - http://localhost:None "PUT /v1.41/containers/028da56e375f70211be4c4a9c9c                                                      a87220f2418bc3e1aefae3509c64dc9a43d81/archive?path=%2F HTTP/1.1" 200 0
DEBUG - Starting device `router`...
DEBUG - http://localhost:None "POST /v1.41/containers/028da56e375f70211be4c4a9c9                                                      ca87220f2418bc3e1aefae3509c64dc9a43d81/start HTTP/1.1" 204 0
DEBUG - http://localhost:None "POST /v1.41/networks/2fb6a6f488d6c9018522b42f67f4                                                      e68e93f10e5c65c102d8cab17ab3d99274ee/connect HTTP/1.1" 200 0
DEBUG - http://localhost:None "POST /v1.41/containers/028da56e375f70211be4c4a9c9                                                      ca87220f2418bc3e1aefae3509c64dc9a43d81/exec HTTP/1.1" 201 74
DEBUG - http://localhost:None "POST /v1.41/exec/000c7110ea6fdade836143df5a0e74df                                                      dbb088c627b4ef0d9dd3281f83e50c61/start HTTP/1.1" 200 0
DEBUG - http://localhost:None "GET /v1.41/exec/000c7110ea6fdade836143df5a0e74dfd                                                      bb088c627b4ef0d9dd3281f83e50c61/json HTTP/1.1" 200 1130
Deploying devices... |                                                   | 0/26
DEBUG - Creating device `device1`...
DEBUG - http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&                                                      trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22app%3Dkathara%22%2C+%22user%3Dubuntu                                                      -rggnnirbwhynneti9hisw%22%2C+%22lab_hash%3DIc4jpIN2IiiYvWa211oIOg%22%2C+%22name%                                                      3Ddevice1%22%5D%7D HTTP/1.1" 200 3
DEBUG - http://localhost:None "POST /v1.41/containers/create?name=kathara_ubuntu                                                      -rggnnirbwhynneti9hisw_device1_Ic4jpIN2IiiYvWa211oIOg HTTP/1.1" 201 88
DEBUG - http://localhost:None "GET /v1.41/containers/301bcccd8ccfcf71c5df18a10d2                                                      bb4f0aede286dae9543b930781b4042fb087e/json HTTP/1.1" 200 None
DEBUG - is_binary: '/home/ubuntu/kathara/lab/device1.startup'
DEBUG - nontext_ratio1: 0.0
DEBUG - nontext_ratio2: 1.0
DEBUG - is_likely_binary: False
DEBUG - detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language':                                                       ''}
DEBUG - failure: decodable_as_unicode: False
DEBUG - http://localhost:None "PUT /v1.41/containers/301bcccd8ccfcf71c5df18a10d2                                                      bb4f0aede286dae9543b930781b4042fb087e/archive?path=%2F HTTP/1.1" 200 0
DEBUG - Starting device `device1`...
DEBUG - http://localhost:None "POST /v1.41/containers/301bcccd8ccfcf71c5df18a10d                                                      2bb4f0aede286dae9543b930781b4042fb087e/start HTTP/1.1" 204 0
DEBUG - http://localhost:None "POST /v1.41/containers/301bcccd8ccfcf71c5df18a10d                                                      2bb4f0aede286dae9543b930781b4042fb087e/exec HTTP/1.1" 201 74
DEBUG - http://localhost:None "POST /v1.41/exec/bcfd8bf216844e2b8d29a9f0233bb563                                                      08441524dc89bbcf525fdcc4f79b04e8/start HTTP/1.1" 200 0
DEBUG - http://localhost:None "GET /v1.41/exec/bcfd8bf216844e2b8d29a9f0233bb5630                                                      8441524dc89bbcf525fdcc4f79b04e8/json HTTP/1.1" 200 1136
Deploying devices... |###                                                | 2/26
DEBUG - Creating device `device2`...
DEBUG - http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&                                                      trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22app%3Dkathara%22%2C+%22user%3Dubuntu                                                      -rggnnirbwhynneti9hisw%22%2C+%22lab_hash%3DIc4jpIN2IiiYvWa211oIOg%22%2C+%22name%                                                      3Ddevice2%22%5D%7D HTTP/1.1" 200 3
DEBUG - http://localhost:None "POST /v1.41/containers/create?name=kathara_ubuntu                                                      -rggnnirbwhynneti9hisw_device2_Ic4jpIN2IiiYvWa211oIOg HTTP/1.1" 201 88
DEBUG - http://localhost:None "GET /v1.41/containers/9d60a65c6e106787637416cd973                                                      9692dbde345a9180db0715d9dffc64276dd26/json HTTP/1.1" 200 None
DEBUG - is_binary: '/home/ubuntu/kathara/lab/device2.startup'
DEBUG - nontext_ratio1: 0.0
DEBUG - nontext_ratio2: 1.0
DEBUG - is_likely_binary: False
DEBUG - detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language':                                                       ''}
DEBUG - failure: decodable_as_unicode: False
DEBUG - http://localhost:None "PUT /v1.41/containers/9d60a65c6e106787637416cd973                                                      9692dbde345a9180db0715d9dffc64276dd26/archive?path=%2F HTTP/1.1" 200 0
DEBUG - Starting device `device2`...
DEBUG - http://localhost:None "POST /v1.41/containers/9d60a65c6e106787637416cd97                                                      39692dbde345a9180db0715d9dffc64276dd26/start HTTP/1.1" 204 0
DEBUG - http://localhost:None "POST /v1.41/containers/9d60a65c6e106787637416cd97                                                      39692dbde345a9180db0715d9dffc64276dd26/exec HTTP/1.1" 201 74
DEBUG - http://localhost:None "POST /v1.41/exec/ab25d6d3224ead5b08a240fe7fa96463                                                      63e35fe4e72e37a25ed0799778799f5f/start HTTP/1.1" 200 0
DEBUG - http://localhost:None "GET /v1.41/exec/ab25d6d3224ead5b08a240fe7fa964636                                                      3e35fe4e72e37a25ed0799778799f5f/json HTTP/1.1" 200 1136
Deploying devices... |#####                                              | 3/26
DEBUG - Creating device `device3`...
DEBUG - http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&                                                      trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22app%3Dkathara%22%2C+%22user%3Dubuntu                                                      -rggnnirbwhynneti9hisw%22%2C+%22lab_hash%3DIc4jpIN2IiiYvWa211oIOg%22%2C+%22name%                                                      3Ddevice3%22%5D%7D HTTP/1.1" 200 3
DEBUG - http://localhost:None "POST /v1.41/containers/create?name=kathara_ubuntu                                                      -rggnnirbwhynneti9hisw_device3_Ic4jpIN2IiiYvWa211oIOg HTTP/1.1" 201 88
DEBUG - http://localhost:None "GET /v1.41/containers/2699ece866f1022a9a2077f45e7                                                      bfb28a71d8085372cbebbfc83aab192fc08c1/json HTTP/1.1" 200 None
DEBUG - is_binary: '/home/ubuntu/kathara/lab/device3.startup'
DEBUG - nontext_ratio1: 0.0
DEBUG - nontext_ratio2: 1.0
DEBUG - is_likely_binary: False
DEBUG - detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language':                                                       ''}
DEBUG - failure: decodable_as_unicode: False
DEBUG - http://localhost:None "PUT /v1.41/containers/2699ece866f1022a9a2077f45e7                                                      bfb28a71d8085372cbebbfc83aab192fc08c1/archive?path=%2F HTTP/1.1" 200 0
DEBUG - Starting device `device3`...
DEBUG - http://localhost:None "POST /v1.41/containers/2699ece866f1022a9a2077f45e                                                      7bfb28a71d8085372cbebbfc83aab192fc08c1/start HTTP/1.1" 204 0
DEBUG - http://localhost:None "POST /v1.41/containers/2699ece866f1022a9a2077f45e                                                      7bfb28a71d8085372cbebbfc83aab192fc08c1/exec HTTP/1.1" 201 74
DEBUG - http://localhost:None "POST /v1.41/exec/76605ec24f1705e473dacd77212f6fed                                                      9cb6971bbba954a4c0ab6368693352a2/start HTTP/1.1" 200 0
DEBUG - http://localhost:None "GET /v1.41/exec/76605ec24f1705e473dacd77212f6fed9                                                      cb6971bbba954a4c0ab6368693352a2/json HTTP/1.1" 200 1136
Deploying devices... |#######                                            | 4/26
DEBUG - Creating device `device4`...
DEBUG - http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&                                                      trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22app%3Dkathara%22%2C+%22user%3Dubuntu                                                      -rggnnirbwhynneti9hisw%22%2C+%22lab_hash%3DIc4jpIN2IiiYvWa211oIOg%22%2C+%22name%                                                      3Ddevice4%22%5D%7D HTTP/1.1" 200 3
DEBUG - http://localhost:None "POST /v1.41/containers/create?name=kathara_ubuntu                                                      -rggnnirbwhynneti9hisw_device4_Ic4jpIN2IiiYvWa211oIOg HTTP/1.1" 201 88
DEBUG - http://localhost:None "GET /v1.41/containers/48baec6313a0da5b36304774256                                                      3eaa8d030a10b2a27bddbc41e96d18a4cec62/json HTTP/1.1" 200 None
DEBUG - is_binary: '/home/ubuntu/kathara/lab/device4.startup'
DEBUG - nontext_ratio1: 0.0
DEBUG - nontext_ratio2: 1.0
DEBUG - is_likely_binary: False
DEBUG - detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language':                                                       ''}
DEBUG - failure: decodable_as_unicode: False
DEBUG - http://localhost:None "PUT /v1.41/containers/48baec6313a0da5b36304774256                                                      3eaa8d030a10b2a27bddbc41e96d18a4cec62/archive?path=%2F HTTP/1.1" 200 0
DEBUG - Starting device `device4`...
DEBUG - http://localhost:None "POST /v1.41/containers/48baec6313a0da5b3630477425                                                      63eaa8d030a10b2a27bddbc41e96d18a4cec62/start HTTP/1.1" 204 0
DEBUG - http://localhost:None "POST /v1.41/containers/48baec6313a0da5b3630477425                                                      63eaa8d030a10b2a27bddbc41e96d18a4cec62/exec HTTP/1.1" 201 74
DEBUG - http://localhost:None "POST /v1.41/exec/55be32d049559c9705addbd6b2017978                                                      7377fdc26a54aec63c7de4c9c6eaa106/start HTTP/1.1" 200 0
DEBUG - http://localhost:None "GET /v1.41/exec/55be32d049559c9705addbd6b20179787                                                      377fdc26a54aec63c7de4c9c6eaa106/json HTTP/1.1" 200 1136
Deploying devices... |#########                                          | 5/26
DEBUG - Creating device `device5`...
DEBUG - http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&                                                      trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22app%3Dkathara%22%2C+%22user%3Dubuntu                                                      -rggnnirbwhynneti9hisw%22%2C+%22lab_hash%3DIc4jpIN2IiiYvWa211oIOg%22%2C+%22name%                                                      3Ddevice5%22%5D%7D HTTP/1.1" 200 3
DEBUG - http://localhost:None "POST /v1.41/containers/create?name=kathara_ubuntu                                                      -rggnnirbwhynneti9hisw_device5_Ic4jpIN2IiiYvWa211oIOg HTTP/1.1" 201 88
DEBUG - http://localhost:None "GET /v1.41/containers/71fa2abd4720df42cd322c736a4                                                      66837c557330048797b416ec3c5f4f8a420b6/json HTTP/1.1" 200 None
DEBUG - is_binary: '/home/ubuntu/kathara/lab/device5.startup'
DEBUG - nontext_ratio1: 0.0
DEBUG - nontext_ratio2: 1.0
DEBUG - is_likely_binary: False
DEBUG - detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language':                                                       ''}
DEBUG - failure: decodable_as_unicode: False
DEBUG - http://localhost:None "PUT /v1.41/containers/71fa2abd4720df42cd322c736a4                                                      66837c557330048797b416ec3c5f4f8a420b6/archive?path=%2F HTTP/1.1" 200 0
DEBUG - Starting device `device5`...
DEBUG - http://localhost:None "POST /v1.41/containers/71fa2abd4720df42cd322c736a                                                      466837c557330048797b416ec3c5f4f8a420b6/start HTTP/1.1" 204 0
DEBUG - http://localhost:None "POST /v1.41/containers/71fa2abd4720df42cd322c736a                                                      466837c557330048797b416ec3c5f4f8a420b6/exec HTTP/1.1" 201 74
DEBUG - http://localhost:None "POST /v1.41/exec/ebe5c351a1161b4012cc22fd79e5c421                                                      8c88d6fee907fb30d3c38572fb49fb17/start HTTP/1.1" 200 0
DEBUG - http://localhost:None "GET /v1.41/exec/ebe5c351a1161b4012cc22fd79e5c4218                                                      c88d6fee907fb30d3c38572fb49fb17/json HTTP/1.1" 200 1136
Deploying devices... |###########                                        | 6/26
DEBUG - Creating device `device6`...
DEBUG - http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&                                                      trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22app%3Dkathara%22%2C+%22user%3Dubuntu                                                      -rggnnirbwhynneti9hisw%22%2C+%22lab_hash%3DIc4jpIN2IiiYvWa211oIOg%22%2C+%22name%                                                      3Ddevice6%22%5D%7D HTTP/1.1" 200 3
DEBUG - http://localhost:None "POST /v1.41/containers/create?name=kathara_ubuntu                                                      -rggnnirbwhynneti9hisw_device6_Ic4jpIN2IiiYvWa211oIOg HTTP/1.1" 201 88
DEBUG - http://localhost:None "GET /v1.41/containers/95de003d8d3f6d840a70a7ae10a                                                      24f0faa8eed799573136b8d66d74fd78cdf95/json HTTP/1.1" 200 None
DEBUG - is_binary: '/home/ubuntu/kathara/lab/device6.startup'
DEBUG - nontext_ratio1: 0.0
DEBUG - nontext_ratio2: 1.0
DEBUG - is_likely_binary: False
DEBUG - detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language':                                                       ''}
DEBUG - failure: decodable_as_unicode: False
DEBUG - http://localhost:None "PUT /v1.41/containers/95de003d8d3f6d840a70a7ae10a                                                      24f0faa8eed799573136b8d66d74fd78cdf95/archive?path=%2F HTTP/1.1" 200 0
DEBUG - Starting device `device6`...
DEBUG - http://localhost:None "POST /v1.41/containers/95de003d8d3f6d840a70a7ae10                                                      a24f0faa8eed799573136b8d66d74fd78cdf95/start HTTP/1.1" 204 0
DEBUG - http://localhost:None "POST /v1.41/containers/95de003d8d3f6d840a70a7ae10                                                      a24f0faa8eed799573136b8d66d74fd78cdf95/exec HTTP/1.1" 201 74
DEBUG - http://localhost:None "POST /v1.41/exec/95af61b02e4f6e50aacdefa5bb247b80                                                      75d7fb26f90c48abbfcf2c63431d1e00/start HTTP/1.1" 200 0
DEBUG - http://localhost:None "GET /v1.41/exec/95af61b02e4f6e50aacdefa5bb247b807                                                      5d7fb26f90c48abbfcf2c63431d1e00/json HTTP/1.1" 200 1136
Deploying devices... |#############                                      | 7/26
DEBUG - Creating device `device7`...
DEBUG - http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&                                                      trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22app%3Dkathara%22%2C+%22user%3Dubuntu                                                      -rggnnirbwhynneti9hisw%22%2C+%22lab_hash%3DIc4jpIN2IiiYvWa211oIOg%22%2C+%22name%                                                      3Ddevice7%22%5D%7D HTTP/1.1" 200 3
DEBUG - http://localhost:None "POST /v1.41/containers/create?name=kathara_ubuntu                                                      -rggnnirbwhynneti9hisw_device7_Ic4jpIN2IiiYvWa211oIOg HTTP/1.1" 201 88
DEBUG - http://localhost:None "GET /v1.41/containers/c4a097a6c9d2fe59ab35b20a06a                                                      baf01d33173147a13a797c570167731237ee3/json HTTP/1.1" 200 None
DEBUG - is_binary: '/home/ubuntu/kathara/lab/device7.startup'
DEBUG - nontext_ratio1: 0.0
DEBUG - nontext_ratio2: 1.0
DEBUG - is_likely_binary: False
DEBUG - detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language':                                                       ''}
DEBUG - failure: decodable_as_unicode: False
DEBUG - http://localhost:None "PUT /v1.41/containers/c4a097a6c9d2fe59ab35b20a06a                                                      baf01d33173147a13a797c570167731237ee3/archive?path=%2F HTTP/1.1" 200 0
DEBUG - Starting device `device7`...
DEBUG - http://localhost:None "POST /v1.41/containers/c4a097a6c9d2fe59ab35b20a06                                                      abaf01d33173147a13a797c570167731237ee3/start HTTP/1.1" 204 0
DEBUG - http://localhost:None "POST /v1.41/containers/c4a097a6c9d2fe59ab35b20a06                                                      abaf01d33173147a13a797c570167731237ee3/exec HTTP/1.1" 201 74
DEBUG - http://localhost:None "POST /v1.41/exec/32ac9d4b2b90e30aecc32f8ffbcc1ffe                                                      39b8bfa5b08edfbb7a3e4748770ec11a/start HTTP/1.1" 200 0
DEBUG - http://localhost:None "GET /v1.41/exec/32ac9d4b2b90e30aecc32f8ffbcc1ffe3                                                      9b8bfa5b08edfbb7a3e4748770ec11a/json HTTP/1.1" 200 1136
Deploying devices... |###############                                    | 8/26
DEBUG - Creating device `device8`...
DEBUG - http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&                                                      trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22app%3Dkathara%22%2C+%22user%3Dubuntu                                                      -rggnnirbwhynneti9hisw%22%2C+%22lab_hash%3DIc4jpIN2IiiYvWa211oIOg%22%2C+%22name%                                                      3Ddevice8%22%5D%7D HTTP/1.1" 200 3
DEBUG - http://localhost:None "POST /v1.41/containers/create?name=kathara_ubuntu                                                      -rggnnirbwhynneti9hisw_device8_Ic4jpIN2IiiYvWa211oIOg HTTP/1.1" 201 88
DEBUG - http://localhost:None "GET /v1.41/containers/34b4f4688dbfe8f26886b587740                                                      cea309d2bdadee3be4aeedc7eda6ff8b55fd6/json HTTP/1.1" 200 None
DEBUG - is_binary: '/home/ubuntu/kathara/lab/device8.startup'
DEBUG - nontext_ratio1: 0.0
DEBUG - nontext_ratio2: 1.0
DEBUG - is_likely_binary: False
DEBUG - detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language':                                                       ''}
DEBUG - failure: decodable_as_unicode: False
DEBUG - http://localhost:None "PUT /v1.41/containers/34b4f4688dbfe8f26886b587740                                                      cea309d2bdadee3be4aeedc7eda6ff8b55fd6/archive?path=%2F HTTP/1.1" 200 0
DEBUG - Starting device `device8`...
DEBUG - http://localhost:None "POST /v1.41/containers/34b4f4688dbfe8f26886b58774                                                      0cea309d2bdadee3be4aeedc7eda6ff8b55fd6/start HTTP/1.1" 204 0
DEBUG - http://localhost:None "POST /v1.41/containers/34b4f4688dbfe8f26886b58774                                                      0cea309d2bdadee3be4aeedc7eda6ff8b55fd6/exec HTTP/1.1" 201 74
DEBUG - http://localhost:None "POST /v1.41/exec/5da2260da4eedc31b86df1bab2091a90                                                      5b612e5f3be53032fac10a38f60a7e1b/start HTTP/1.1" 200 0
DEBUG - http://localhost:None "GET /v1.41/exec/5da2260da4eedc31b86df1bab2091a905                                                      b612e5f3be53032fac10a38f60a7e1b/json HTTP/1.1" 200 1136
Deploying devices... |#################                                  | 9/26
DEBUG - Creating device `device9`...
DEBUG - http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&                                                      trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22app%3Dkathara%22%2C+%22user%3Dubuntu                                                      -rggnnirbwhynneti9hisw%22%2C+%22lab_hash%3DIc4jpIN2IiiYvWa211oIOg%22%2C+%22name%                                                      3Ddevice9%22%5D%7D HTTP/1.1" 200 3
DEBUG - http://localhost:None "POST /v1.41/containers/create?name=kathara_ubuntu                                                      -rggnnirbwhynneti9hisw_device9_Ic4jpIN2IiiYvWa211oIOg HTTP/1.1" 201 88
DEBUG - http://localhost:None "GET /v1.41/containers/87d1a27e550dcb76fe7fc719e88                                                      3d608f4362cef68062614e53fc31f3717f402/json HTTP/1.1" 200 None
DEBUG - is_binary: '/home/ubuntu/kathara/lab/device9.startup'
DEBUG - nontext_ratio1: 0.0
DEBUG - nontext_ratio2: 1.0
DEBUG - is_likely_binary: False
DEBUG - detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language':                                                       ''}
DEBUG - failure: decodable_as_unicode: False
DEBUG - http://localhost:None "PUT /v1.41/containers/87d1a27e550dcb76fe7fc719e88                                                      3d608f4362cef68062614e53fc31f3717f402/archive?path=%2F HTTP/1.1" 200 0
DEBUG - Starting device `device9`...
DEBUG - http://localhost:None "POST /v1.41/containers/87d1a27e550dcb76fe7fc719e8                                                      83d608f4362cef68062614e53fc31f3717f402/start HTTP/1.1" 204 0
DEBUG - http://localhost:None "POST /v1.41/containers/87d1a27e550dcb76fe7fc719e8                                                      83d608f4362cef68062614e53fc31f3717f402/exec HTTP/1.1" 201 74
DEBUG - http://localhost:None "POST /v1.41/exec/159a9589788bb089d4586fd0c28a8b64                                                      72a5153c0583db48e3509813b0b17a07/start HTTP/1.1" 200 0
DEBUG - http://localhost:None "GET /v1.41/exec/159a9589788bb089d4586fd0c28a8b647                                                      2a5153c0583db48e3509813b0b17a07/json HTTP/1.1" 200 1136
Deploying devices... |###################                               | 10/26
DEBUG - Creating device `device10`...
DEBUG - http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&                                                      trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22app%3Dkathara%22%2C+%22user%3Dubuntu                                                      -rggnnirbwhynneti9hisw%22%2C+%22lab_hash%3DIc4jpIN2IiiYvWa211oIOg%22%2C+%22name%                                                      3Ddevice10%22%5D%7D HTTP/1.1" 200 3
DEBUG - http://localhost:None "POST /v1.41/containers/create?name=kathara_ubuntu-rggnnirbwhynneti9hisw_device10_Ic4jpIN2IiiYvWa211oIOg HTTP/1.1" 201 88
DEBUG - http://localhost:None "GET /v1.41/containers/e501695413be50edd698c7e7c18f6316aac1d3bb510383415b662c1650ced3cf/json HTTP/1.1" 200 None
DEBUG - is_binary: '/home/ubuntu/kathara/lab/device10.startup'
DEBUG - nontext_ratio1: 0.0
DEBUG - nontext_ratio2: 1.0
DEBUG - is_likely_binary: False
DEBUG - detected_encoding: {'encoding': 'ascii', 'confidence': 1.0, 'language': ''}
DEBUG - failure: decodable_as_unicode: False

**Comment by lorenzo93** [comment]
Hi @slasom,

even from this log we were unable to find the problem.
To help you further, the best way is to schedule a private meeting.

So, if you want our help, write us an email to contact@kathara.org so we can arrange the details :)

Thanks
Lorenzo

**Comment by slasom** [comment]
Okey perfect! Thank you so much!

**Comment by slasom** [comment]
I have contacted you but have not received a reply.

**Comment by lorenzo93** [comment]
Hi @slasom,

I'm sorry, your email ended up in the spam folder.
I'm replying right now!
