### ISSUE TITLE
How to get a list of collision domains via API?

### ISSUE THREAD

**Issue by zhangineer2** [KatharaFramework/Kathara#149]
hello, I wonder if there is a quick way to get a list of collision domains. 

I tried the following in the API:

```
from Kathara.manager.docker.DockerManager import DockerManager
docker_manager = DockerManager()
print(docker_manager.client.networks.list())
```

and received the following

```
[<Network: 095e05a32c>, <Network: c45dbda0e0>, <Network: 545c3a5877>, <Network: 1b9d6db5ae>, <Network: be46e4a478>, <Network: caab7b7e01>, <Network: 1e5f8fd582>, <Network: 61b142baa8>, <Network: a6aee967e2>, <Network: 4f392d2609>, <Network: c44975ef68>, <Network: e27a15e08b>, <Network: 26f42974a1>, <Network: e9eeb060c7>, <Network: 4be839bbd7>, <Network: 4dff7eeffb>, <Network: 95e03e89ea>, <Network: 588837aa6a>, <Network: b35dc99397>, <Network: 09c1910176>, <Network: 0619e5b64a>, <Network: ec5b702b07>]
```

However, is there a better way to get what's shown via the `docker network list` via API so that I can better print it out or filter it ?

Thank you

**Comment by Skazza94** [comment]
Hi @zhangineer,
if you want the collision domains of a specific lab, after deploying it with `Kathara.get_instance().deploy_lab`, you can access them from `lab.links` dict. The dict contains the name of the collision domain as key,  and a `Link` object as value.
The `Link` object has the `api_object` attribute, which is the representation of the network for the specified Manager (e.g., Docker Network, or Kubernetes Network Definition). This attribute is populated after deploying the lab:

```python3
from Kathara.manager.Kathara import Kathara
from Kathara.model.Lab import Lab

lab = Lab("Test")
h1 = lab.get_or_new_machine('h1')
lab.connect_machine_to_link('h1', 'A', 0)
Kathara.get_instance().deploy_lab(lab)

collision_domains = lab.links.values()
```

If you want to access all the collision domains (like `docker network ls`), currently there's no way to fetch them. However, it would be convenient to have a method from the `Kathara` facade to retrieve all the CDs (like `get_machine_info` or `get_machine_api_object` for the devices). So I'll work on that and add it in the future release.

**Comment by zhangineer2** [comment]
Hello @Skazza94 

thanks for the info, if I want to get links.values for an existing lab, how can I retrieve such information ?

Thanks
Peter

**Comment by zhangineer2** [comment]
Also, I tested `lab.links.values()` today and was only getting the following, which does not show me actual interfaces being linked. I would expect to see something like `(h1,0)` as part of collision domain A.

dict_values([Link(A, []), Link(kathara_host_bridge, [])])

**Comment by Skazza94** [comment]
Hello @zhangineer,
as I said, there's no way to retrieve the CDs of a lab already deployed.

Me and @tcaiazzi we'll address this issue by refactoring the Manager classes and exposing better methods (see #154).

Sorry for the inconvenience,
Mariano

**Comment by Skazza94** [comment]
Hi @zhangineer,
in version 3.5.0, you can find new Manager APIs to retrieve collision domains information. In particular, these new methods will return Docker/Kubernetes Network objects (depending on the chosen Manager).
For Docker, a description of the class can be found [here](https://docker-py.readthedocs.io/en/stable/networks.html#network-objects).

As an example:
```python
from Kathara.manager.Kathara import Kathara
from Kathara.model.Lab import Lab

lab = Lab("Test")
h1 = lab.get_or_new_machine('h1')
lab.connect_machine_to_link('h1', 'A')
h2 = lab.get_or_new_machine('h2')
lab.connect_machine_to_link('h2', 'A')
lab.connect_machine_to_link('h2', 'B')
Kathara.get_instance().deploy_lab(lab)

# Retrieve information of collision domain A
cd_a = Kathara.get_instance().get_link_api_object(link_name="A", lab_name="Test")

# Retrieve information of all collision domains
cds = Kathara.get_instance().get_link_api_object(lab_name="Test")
```

If you need further help, don't hesitate to open a new issue, and thanks a lot for you support, you help has been crucial in improving Python APIs!
