### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by zhangineer2** [KatharaFramework/Kathara#158]
Hello

Is there a way to add environment variables when starting a docker container?
I know I can achieve this by setting it as part of the image, but would be nice to have a bit more flexibility to set it when starting a container.

Thanks
Peter

**Comment by tcaiazzi** [comment]
Hi @zhangineer,

We implemented this feature recently in the [feature-env](https://github.com/KatharaFramework/Kathara/tree/feature-env) branch. It is already merged in the [develop](https://github.com/KatharaFramework/Kathara/tree/develop) branch.
So, it will be officially available in the next release (soon). 

Thanks for the support, 
Tommaso
