### ISSUE TITLE
Create OVS ports even with no device attached

### ISSUE THREAD

**Issue by zhangineer2** [KatharaFramework/Kathara#160]
Hello:

Is there a way to leave ports "open" with no devices attached? For example, I want to create a switch with 12 ports, with the first 6 ports reserved for switch-to-switch connections, and the remaining 6 for host connections only. Hence I am specifically assigning ports. However, I noticed that if the port is not added to any collision domain, it will not even get created on the OVS, and Kathara would just assign ports in sequence.

I can think of one way to work around this is to add all "open ports" to a single collision domain, much like connecting all ports to a default "VLAN 1". 

Is there a better way of doing this?

Thank you.

Here is the output from one of my switches

```
root@s11:/# ovs-vsctl show
04bf9317-af60-461c-97dc-c8e0b7ac5cb9
    Bridge ovs-br
        Controller "tcp:192.168.0.254:6633"
            is_connected: true
        Port "eth5"
            Interface "eth5"
                error: "could not open network device eth5 (No such device)"
        Port "eth8"
            Interface "eth8"
                error: "could not open network device eth8 (No such device)"
        Port "eth10"
            Interface "eth10"
                error: "could not open network device eth10 (No such device)"
        Port "eth6"
            Interface "eth6"
                error: "could not open network device eth6 (No such device)"
        Port "eth9"
            Interface "eth9"
                error: "could not open network device eth9 (No such device)"
        Port "eth12"
            Interface "eth12"
                error: "could not open network device eth12 (No such device)"
        Port "eth4"
            Interface "eth4"
                error: "could not open network device eth4 (No such device)"
        Port "eth3"
            Interface "eth3"
        Port "eth7"
            Interface "eth7"
                error: "could not open network device eth7 (No such device)"
        Port "eth11"
            Interface "eth11"
                error: "could not open network device eth11 (No such device)"
        Port ovs-br
            Interface ovs-br
                type: internal
        Port "eth1"
            Interface "eth1"
        Port "eth2"
            Interface "eth2"
    ovs_version: "2.10.7"
root@s11:/# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.11  netmask 255.255.255.0  broadcast 192.168.0.255
        ether fa:28:6a:3b:95:61  txqueuelen 1000  (Ethernet)
        RX packets 175051  bytes 19226960 (18.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2414  bytes 255682 (249.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 72:15:8e:f2:94:03  txqueuelen 1000  (Ethernet)
        RX packets 309  bytes 18540 (18.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 307  bytes 18420 (17.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth2: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether d2:69:03:4e:ef:43  txqueuelen 1000  (Ethernet)
        RX packets 311  bytes 18660 (18.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 307  bytes 18420 (17.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether ee:9e:34:d2:66:14  txqueuelen 1000  (Ethernet)
        RX packets 307  bytes 18420 (17.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 308  bytes 18480 (18.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by zhangineer2** [comment]
Hello

I am trying a method where I would initialize all switch ports first, as follow:

This creates port 1 - 12 and add them to collision domain "ground_zero"
```
        for i in range(1,13):
            self.lab.connect_machine_to_link(self.node.name, "ground_zero", i)
```

So my question now becomes, how do I reconnect a port to a new collision domain? I can't use the method `connect_machine_to_link` due to the port already assigned to a CD. is there a method to update? or maybe remove and add?

Thank you

**Comment by Skazza94** [comment]
Hi @zhangineer,
by definition, each interface of a Kathará device must be attached to a collision domain.
However, it is possible to attach additional interfaces after the lab has been deployed.

To do so, you can use the `lconfig` command from CLI. 
Suppose that you have `s11` with 4 interfaces as your example above. You can add 2 interfaces on collision domains `Y` and `Z`, typing the following:
```bash
kathara lconfig -n s11 --eth Y Z
```
At this point, `eth4` (on collision domain `Y`) and `eth5` (on collision domain `Z`) are added.

You can achieve the same result from Python APIs using the `update_lab` method from `Kathara` facade.
Suppose that you have a deployed network scenario with name `lab`, the `update_lab` takes a diff of the current device, adding missing interfaces.
```python3
lab = Lab("lab")
s11 = lab.get_or_new_machine('s11')

# Add Interfaces, they're automatically appended to existing ones.
lab.connect_machine_to_link('s11', 'Y')
lab.connect_machine_to_link('s11', 'Z')
Kathara.get_instance().update_lab(lab)
```

We're still working to make possible to disconnect interfaces from collision domains, and probably it'll be added as a feature in future releases.

**Comment by zhangineer2** [comment]
Hi @Skazza94 

My issue is that I am building Kathara from a static database. I am using Kathara far more than just a "lab" environment actually. Every device to be attached to the OVS in Kathara has specific port assignment. 

When I get a list of links to be deployed from a database, I often get un-ordered data, such as
```
s1/eth2-h2/eth0
s1/eth1-h1/eth0
s1/eth3-h3/eth0
```

by Kathara's logic, it would've ended up like this
```
s1/eth1-h2/eth0
s1/eth2-h1/eth0
s1/eth3-h3/eth0
```
I hope there is a way like in Mininet where you can statically assign ports

Thanks

**Comment by Skazza94** [comment]
Hi @zhangineer,
sorry for the late reply. The interface ordering is not a Kathará-related issue, but a Docker one (see https://github.com/moby/moby/issues/25181). 

So, to circumvent this limitation, we enforce the interface ordering before the container deployment, during the lab parsing. In this way, we avoid non-deterministic behaviours in interfaces number assignment.

In conclusion, the solution for your problem is to order the interfaces when retrieving them from the database, or using python `sorted` on the database result. :smile:
