### ISSUE TITLE
Nagios compatibility 

### ISSUE THREAD

**Issue by ciociolin** [KatharaFramework/Kathara#162]
Is it possible to set up a Nagios monitorization on Kathara devices? Either by monitoring from the host or from one of the lab machines.
One issue i face when trying is receiving connection refused on port 5666 when trying to use nrpe.

**Comment by Skazza94** [comment]
Hi @ciociolin,
we never tested Nagios compatibility with Kathará. 
However, you can post here an example lab and we'll try to solve your issue 😄 

Mariano.

**Comment by Skazza94** [comment]
Since the last reply was 21 days ago, I'm considering the issue as solved or no longer relevant.

If you need further support, you can reopen the issue.

Thanks!
