### ISSUE TITLE
Support for Ubuntu 22.04 - Jellyfish

### ISSUE THREAD

**Issue by whatever4711** [KatharaFramework/Kathara#164]
**Is your feature request related to a problem? Please describe.**
Currently, Kathara is not installable on Ubuntu 22.04

**Describe the solution you'd like**
Support for Ubuntu 22.04...

**Comment by tcaiazzi** [comment]
Hi @whatever4711 , 

We are working on it now! 

We will release a new version (also for Ubuntu 22.04) as soon as possible! 

Thanks for the support, 
Tommaso

**Comment by tcaiazzi** [comment]
Hi @whatever4711,

we released a new version (3.5.0) that includes the support for Ubuntu 22.04. 

Thanks, 
Tommaso

**Comment by whatever4711** [comment]
Thank you so much, Tommaso. My students appreciate your fast response.
