### ISSUE TITLE
Env Regex Match failure

### ISSUE THREAD

**Issue by zhangineer2** [KatharaFramework/Kathara#168]
in the `machine.py` file
the regex for `env` is `^(?P<key>\w+)=(?P<value>\w+)$`
which does not accurately match IP addresses as a value. I don't think IP addresses will ever be a key.

the following worked for me

`^(?P<key>\w+)=(?P<value>\w+.*)$`

**Comment by Skazza94** [comment]
Hi @zhangineer,
thanks for the issue. I'll open a branch and fix the regex.

Mariano.

**Comment by Skazza94** [comment]
Hi @zhangineer,
you can find the fix in the `develop` branch. We'll merge it in the next release.

Thanks!
