### ISSUE TITLE
Generating packets into and within Kathara

### ISSUE THREAD

**Issue by iustin541** [KatharaFramework/Kathara#176]
Hello,

I'm sorry if this wasn't the place to post this, it's my first time using Github.

I'm trying for a project to create a mini-network using kathara and what I need to do is to generate raw IPv6 packets into a kathara node, using a non-kathara node.

I am going to develop a physycal/virtual machine tested and a software, whose purpose will be to generate IPv6 traffic packets.
With the help of the developed software, I am going to generate and capture a series of virtually generated IPv6 packets.
The monitored data traffic, which will eventually hop into the actual network, is going to be analyzed.

These packets must be generated and, afterwards, captured and monitored.

Can anybody please help me by letting me know if this thing is possible?

Any kind of help if appreciated. Thank you very much!

**Comment by Skazza94** [comment]
Hi @iustin541,
don't worry, I think this is the right place to post this issue! And welcome to the Kathará community! 😄 

So, basically you want to inject IPv6 packets into a Kathará node from the host.

You have 3 different alternatives to achieve so:
1. You can attach a physical interface of the host to a Kathará collision domain (using `lab.ext`);
2. You can bridge a container to the host network (attaching it to the default Docker bridge);
3. You can put the traffic generator into a Kathará node, and this can be achieved in two different ways: create a new Docker image with the software inside or put the software into the `shared/` folder of the lab.

If you can explain better your use case, even with a picture of the network, we can address you to the right solution.

Thanks,
Mariano.

**Comment by iustin541** [comment]
Hello @Skazza94,

Thank you very much for your help! I have managed to connect the host to the kathara node.

I'm facing another problem, which I couldn't find in the documentation.
I have made an experimental laboratory, with a very small amount of elements.

![2](https://user-images.githubusercontent.com/108490088/179404428-eea1e55d-89a7-4962-bf18-4529bb62c1ab.png)

I'm trying to ping from c1 to c2, using IPv6. Here are the setup files that I have made:

> c1.startup

```
ifconfig eth0 192.168.1.2 netmask 255.255.255.252 up
route add default gw 192.168.1.1
```

> c2.startup

```
ifconfig eth0 192.168.3.2 netmask 255.255.255.252 up
route add default gw 192.168.3.1
```

> r1.startup

```
ifconfig eth0 192.168.1.1 netmask 255.255.255.252 up
ifconfig eth1 192.168.2.1 netmask 255.255.255.252 up

route add -net 192.168.3.0/30 gw 192.168.2.2
```

> r2.startup
```
ifconfig eth0 192.168.2.2 netmask 255.255.255.252 up
ifconfig eth1 192.168.3.1 netmask 255.255.255.252 up

route add -net 192.168.1.0/30 gw 192.168.2.1
```

> lab.conf
```
c1[0]=A
r1[0]=A
r1[1]=B
r2[0]=B
r2[1]=C
c2[0]=C

r1[sysctl]="net.ipv6.conf.all.forwarding=1"
r1[sysctl]="net.ipv6.conf.default.forwarding=1"
r2[sysctl]="net.ipv6.conf.all.forwarding=1"
r2[sysctl]="net.ipv6.conf.default.forwarding=1"
```

When I ping from c1 to c2, everything works just fine:

```
root@c1:/# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.2  netmask 255.255.255.252  broadcast 192.168.1.3
        inet6 fe80::688c:40ff:fe94:a20  prefixlen 64  scopeid 0x20<link>
        ether 6a:8c:40:94:0a:20  txqueuelen 1000  (Ethernet)
```
```
root@c2:/# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.3.2  netmask 255.255.255.252  broadcast 192.168.3.3
        inet6 fe80::ac7f:9cff:fef9:9a08  prefixlen 64  scopeid 0x20<link>
        ether ae:7f:9c:f9:9a:08  txqueuelen 1000  (Ethernet)
```
```
root@c1:/# ping 192.168.3.2
PING 192.168.3.2 (192.168.3.2) 56(84) bytes of data.
64 bytes from 192.168.3.2: icmp_seq=1 ttl=62 time=0.125 ms
64 bytes from 192.168.3.2: icmp_seq=2 ttl=62 time=0.074 ms
64 bytes from 192.168.3.2: icmp_seq=3 ttl=62 time=0.077 ms
64 bytes from 192.168.3.2: icmp_seq=4 ttl=62 time=0.084 ms
^C
--- 192.168.3.2 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 144ms
rtt min/avg/max/mdev = 0.074/0.090/0.125/0.020 ms
```

However, when I try to ping to the IPv6 address of c2, it doesn't work:
```
root@c1:/# ping6 -I eth0 fe80::ac7f:9cff:fef9:9a08
ping6: Warning: source address might be selected on device other than eth0.
PING fe80::ac7f:9cff:fef9:9a08(fe80::ac7f:9cff:fef9:9a08) from :: eth0: 56 data bytes
^C
--- fe80::ac7f:9cff:fef9:9a08 ping statistics ---
4 packets transmitted, 0 received, 100% packet loss, time 100ms
```

Is there an IPv6 static route command that I should apply to the two routers in order for this to work? Am I doing anything wrong? Thanks, wish you a great Sunday!

**Comment by Skazza94** [comment]
Hi @iustin541,
you are using the IPv6 Link Local addresses to ping between the two hosts. However, Link Local addresses can only be used to communicate with hosts in the same collision domain (hence, local 😄).

You have to perform a full IPv6 address assignment (like IPv4) to make it work.

Mariano.

**Comment by iustin541** [comment]
Hello my friend!

Thank you for your answer!

Could you please give me an example of how should I make those configurations on the computers and on the routers? I wasn't able to find anywhere how should I proceed.

**Comment by Skazza94** [comment]
Hi @iustin541,
here's an IPv6 assignment that works:

> c1.startup

```
ifconfig eth0 192.168.1.2 netmask 255.255.255.252 up
route add default gw 192.168.1.1

# IPv6 address and default route
ip addr add 2100::2/64 dev eth0
ip -6 route add default via 2100::1 dev eth0
```

> c2.startup

```
ifconfig eth0 192.168.3.2 netmask 255.255.255.252 up
route add default gw 192.168.3.1

# IPv6 address and default route
ip addr add 2300::2/64 dev eth0
ip -6 route add default via 2300::1 dev eth0
```

> r1.startup

```
ifconfig eth0 192.168.1.1 netmask 255.255.255.252 up
ifconfig eth1 192.168.2.1 netmask 255.255.255.252 up
route add -net 192.168.3.0/30 gw 192.168.2.2

# IPv6 address and routes
ip addr add 2100::1/64 dev eth0
ip addr add 2200::1/64 dev eth1
ip route add 2300::/64 via 2200::2 dev eth1
```

> r2.startup
```
ifconfig eth0 192.168.2.2 netmask 255.255.255.252 up
ifconfig eth1 192.168.3.1 netmask 255.255.255.252 up
route add -net 192.168.1.0/30 gw 192.168.2.1

# IPv6 address and routes
ip addr add 2200::2/64 dev eth0
ip addr add 2300::1/64 dev eth1
ip route add 2100::/64 via 2200::1 dev eth0
```

Ping from c1 to c2 working:
```
root@c1:/# ping6 -I eth0 2300::2
PING 2300::2(2300::2) from 2100::2 eth0: 56 data bytes
64 bytes from 2300::2: icmp_seq=1 ttl=62 time=0.366 ms
64 bytes from 2300::2: icmp_seq=2 ttl=62 time=0.452 ms
64 bytes from 2300::2: icmp_seq=3 ttl=62 time=0.599 ms
64 bytes from 2300::2: icmp_seq=4 ttl=62 time=0.456 ms
^C
--- 2300::2 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 91ms
rtt min/avg/max/mdev = 0.366/0.468/0.599/0.085 ms
```

Hope this solves your problem, so I can close the issue! 😄 
If you have further problems, don't hesitate to reply!

Mariano.

**Comment by iustin541** [comment]
Hello,

Thank you very much, my friend!

You can close this issue for sure, you have been very helpful. I will apply the information provided from you and if there will be any other problem
occuring, I will start a new post. 😁 

Wish you a nice day!
