### ISSUE TITLE
pyuv broken with python 3.10.x

### ISSUE THREAD

**Issue by Mai-Lapyst** [KatharaFramework/Kathara#182]
**Describe the bug**
pyuv is currently broken for python 3.10.x

see upstream issue https://github.com/saghul/pyuv/issues/271 / PR https://github.com/saghul/pyuv/pull/275

**To Reproduce**
1. Clone repo
2. Make venv with python 3.10 & activate it (`python3 -m venv ./venv && source venv/bin/activate`)
3. run `pip install -r src/requirements.txt`
4. pip errors when trying to compile native parts of pyuv

**Temporary Workaround**
Use the master branch of pyuv as this has the changes merges from the PR mentioned above. This means to replace the pyuv line in `requirements.txt` with `git+https://github.com/saghul/pyuv@master#egg=pyuv`.

**Comment by tcaiazzi** [comment]
Hi @Mai-Lapyst,

Many thanks for pointing out this!

We were aware of the problem of `pyuv` with `python3.10`, but we didn't know of the PR that solved it! :smile: 

We will merge your workaround in the next release. 

Thanks, 
Tommaso
