### ISSUE TITLE
Debian 11 installation instructions should be updated (`apt-key` is deprecated)

### ISSUE THREAD

**Issue by b3** [KatharaFramework/Kathara#184]
[Debian 11 installation instructions](https://github.com/KatharaFramework/Kathara/wiki/Linux#debian-11) still says to use `apt-key` while `apt-key` use is now deprecated in Debian as stated in the [man page](https://manpages.debian.org/bullseye/apt/apt-key.8.en.html).

I guess the documentation should looks like something like the following (not sure about `libmpdec3` though).

------------------------------------------------------------------------------
1. Add Kathará public key to your keyring:
    ```bash
     wget -qO - "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x21805a48e6cbba6b991abe76646193862b759810" |
             gpg --dearmor |
             dd of=/usr/share/keyrings/ppa-kathara-archive-keyring.gpg
    ````
2. Add the Kathará repository:
    Create a `kathara.list` file in `/etc/apt/sources.list.d` and put inside the following lines:
    ```
    deb [ signed-by=/usr/share/keyrings/ppa-kathara-archive-keyring.gpg ] http://ppa.launchpad.net/katharaframework/kathara/ubuntu focal main 
    deb-src [ signed-by=/usr/share/keyrings/ppa-kathara-archive-keyring.gpg ] http://ppa.launchpad.net/katharaframework/kathara/ubuntu focal main
    ```
    This can, for instance, be done by running the following commands:
    ```bash
    echo "deb [ signed-by=/usr/share/keyrings/ppa-kathara-archive-keyring.gpg ] http://ppa.launchpad.net/katharaframework/kathara/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/kathara.list
    echo "deb-src [ signed-by=/usr/share/keyrings/ppa-kathara-archive-keyring.gpg ] http://ppa.launchpad.net/katharaframework/kathara/ubuntu focal main" | sudo tee /etc/apt/sources.list.d/kathara.list
    ```
4. Update your apt cache by running `sudo apt update`
5. Install Kathará running `sudo apt install libmpdec3 kathara` 
------------------------------------------------------------------------------

**Comment by tcaiazzi** [comment]
Hi @b3, 
Thanks for notice this! :smile: 

I will update the installation instructions as soon as possible!

Many thanks for the help,
Tommaso

**Comment by tcaiazzi** [comment]
Hi @b3,
I updated the wiki!

I also found that the `libmpdec` dependency is finally fixed, so I removed that part from the instructions!

Many thanks for the help! :rocket: 
Tommaso
