### ISSUE TITLE
Docker 4.12.0 closing PowerShell windows on lab start

### ISSUE THREAD

**Issue by MrSpadala** [KatharaFramework/Kathara#191]
Hi guys

## Problem
When launching, a Katharà laboratory, I observe powershell windows opening, hanging on for a few seconds, and then closing abruptly. 

For a split second before closing, the window prints the following error message:
![powershell_error](https://user-images.githubusercontent.com/23057237/194821416-b1ad5474-2dce-4c8c-a112-0a74df12d37b.png)

## Steps to reproduce
On Windows, using Katharà 3.5.1 and docker 4.12.0. (as of now the latest versions for both docker and kathara).
The file `lab.conf` contains a single line `pc[0]=A`.

## Other info
 - In the background, the kathara laboratory is running, and one can connect successfully with `kathara connect` command.
 - I've tried to use both the administrator's and the normal user's powershell, it didn't work.
 - I wanted to try the option to change the terminal emulator, but at the moment such option exists only on Linux.
 
## Fixes
For the moment, we have managed to fix this problem by installing the previous version of docker 4.11.1

**Comment by tcaiazzi** [comment]
Hi @MrSpadala, 

Thanks for pointing out this.

We also noticed this problem today. It is related to this issue of docker-py: https://github.com/docker/docker-py/issues/3045 

We are working for releasing a fixed version for Windows as soon as possible (probably today).

As you say, for now the only possible fix is to downgrade Docker Desktop to version 4.11.1.

Sorry for the inconvenience,
Tommaso

**Comment by tcaiazzi** [comment]
We released the fixed version. 

We replaced the old Windows installer inside [release 3.5.1](https://github.com/KatharaFramework/Kathara/releases/tag/3.5.1) with a new one: [Kathara-windows-installer-x64-3.5.1-PATCHED.exe](https://github.com/KatharaFramework/Kathara/releases/download/3.5.1/Kathara-windows-installer-x64-3.5.1-PATCHED.exe).

Feel free to re-open this issue if you have other problems. 

Thanks, 
Tommaso

**Comment by MrSpadala** [comment]
Works like a charm 🚀
