### ISSUE TITLE
(SettingsError) Settings file is not valid: Terminal Emulator `/usr/bin/xterm` not valid! Install it before using it. Fix it or delete it before launching.

### ISSUE THREAD

**Issue by HammerIonut2000** [KatharaFramework/Kathara#192]
I've installed docker and kathara on ubuntu virtual machine, and I've tried to run the command: sudo kathara vstart --name container
and after waiting I get this error:

(SettingsError) Settings file is not valid: Terminal Emulator `/usr/bin/xterm` not valid! Install it before using it. Fix it or delete it before launching.

How can I solve it?

**Comment by tcaiazzi** [comment]
Hi @HammerIonut2000, 

`xterm` is the terminal emulator used by Kathará as default. 

As specified in the [installation guide](https://github.com/KatharaFramework/Kathara/wiki/Linux) (and in the error you posted :innocent:), you need to install it to use Kathará  with default settings. 

To install `xterm` type on a terminal:
```bash
sudo apt install xterm
```

Let me know if you need further help,
Tommaso

**Comment by HammerIonut2000** [comment]
Hi @tcaiazzi,

I did it as you said, and it worked. Thx for the solution. :)
