### ISSUE TITLE
Testing network connectivity with ping command problem

### ISSUE THREAD

**Issue by HammerIonut2000** [KatharaFramework/Kathara#193]
I'm trying to test network connectivity for 2 virtual machines and something's not working. Both are sending the packets but none of them receive anything, "100% packet loss". What should I do?

**Comment by tcaiazzi** [comment]
Hi @HammerIonut2000, 

This is not related to a Kathará issue. Probably you are miss-configuring something in your lab.

See our [introduction slides](https://github.com/KatharaFramework/Kathara-Labs/blob/master/001-kathara-introduction.pdf) and our [official labs](https://github.com/KatharaFramework/Kathara-Labs) for some examples. 

Thanks,
Tommaso
