### ISSUE TITLE
Problem with Linux installation 

### ISSUE THREAD

**Issue by ghost** [KatharaFramework/Kathara#20]
Hi, I've followed your Linux installation guide and I've been trying to test if everything went well through the example you give with MARACAS_lab.
I get this series of errors though and I don't know how to fix them: 
![1](https://user-images.githubusercontent.com/32570656/47294973-c4890380-d60e-11e8-99e0-891cd65fb84d.png)

What can I do?

**Comment by ghost** [comment]
Nevermind, solved with $ sudo ln -s /usr/bin/python2 /usr/bin/python --force

**Comment by Kidel** [comment]
it's simply because you're using Python 3 instead of Python 2.

**Comment by Kidel** [comment]
It's probably because you're using Python 3.x instead of 2.x
