### ISSUE TITLE
 Kathara terminal stops printing output of startup commands ran after some time after startup

### ISSUE THREAD

**Issue by fstachura** [KatharaFramework/Kathara#209]
**Describe the bug**
 Kathara terminal stops printing output of startup commands ran after some time after startup

**To Reproduce**
1. Create a directory structure as shown below
2. Run `kathara lstart`
3. Startup script output on `pc1` should show 'text 1' but not 'text 2'
4. Edit `pc1.startup` and change `sleep` value to `0.5`
5. Run `kathara wipe -f && kathara lstart`
6. Startup script output on `pc1` should now show both 'text 1' and 'text 2'

Note: sleep values necessary to trigger this bug might be different depending on platform. For example, on Windows 10 `sleep 1` was short enough for both texts to print, however, `sleep 10` was too long.
In the first scenario, where 'text 2' gets truncated, it is still visible in `/var/log/startup.log`. So it seems that commands are executed, only output gets truncated depending on running time of previous commands.

```
tree
.
├── lab.conf
├── pc1/
├── pc1.startup
└── shared/
```

`lab.conf`:
```
pc1[0]=A
```

`pc1.startup`:
```
echo "text 1"
sleep 1
echo "text 2"
```

**Expected behavior**
Startup script output contains 'text 2' 

**Screenshots**

![Screenshot_20230326_221508_root@pc1: _](https://user-images.githubusercontent.com/55913800/227802552-b42bbc58-93b6-4a43-9b09-1a41f842f712.png)

![Screenshot_20230326_221603_root@pc1: _](https://user-images.githubusercontent.com/55913800/227802554-cbd9b997-9437-4297-8754-3b49cfb9989a.png)

<details>
<summary>"check" Command Output</summary>

```
*       Current Manager is: Docker (Kathara)
*       Manager version is: 23.0.1
*       Python version is: 3.10.7 (main, Dec 28 2022, 15:08:11) [GCC 12.2.0]
*       Kathara version is: 3.5.5
*       Operating System version is: Linux-6.1.15-1-lts-x86_64
*       Trying to run `Hello World` container...
Deploying devices...|###################################################################################################################################################################################################################################################| 1/1
*       Container run successfully.
Deleting devices...|####################################################################################################################################################################################################################################################| 1/1
```

</details>

Tested on Arch Linux (updated today) and Windows 10 (with larger `sleep` values)

**Comment by tcaiazzi** [comment]
Hi @fstachura, 

thanks for opening the issue and sorry for the late reply.

We are discussing to find the right way to fix this problem. 

We will come back soon with a solution :innocent:

**Comment by tcaiazzi** [comment]
Hi @fstachura, 

We decided for waiting the execution of the startup commands on each device unless the user explicitly requests the control over it by pressing a key. 

You can track the changes on the related branch: [209-waiting-startup-on-connect](https://github.com/KatharaFramework/Kathara/tree/209-waiting-startup-on-connect).
