### ISSUE TITLE
problem at the start of kathara on linux

### ISSUE THREAD

**Issue by EmanueleBarbalaco** [KatharaFramework/Kathara#21]
after installation, by executing the command $ NETKIT_HOME / vstart --eth 0: A pc1
the error that appears in the figure is presented
![schermata del 2018-10-22 17-52-30](https://user-images.githubusercontent.com/40856154/47303092-5864ca80-d623-11e8-84e3-5ef452d86138.png)

**Comment by Kidel** [comment]
Hi, try to download the latest version and run `$NETKIT_HOME/lwipe` and `$NETKIT_HOME/install`.

It appears that the installer couldn't write the config file. 

In case it happens again please provide the output of `$NETKIT_HOME/check`

**Comment by EmanueleBarbalaco** [comment]
![schermata del 2018-10-22 18-01-57](https://user-images.githubusercontent.com/40856154/47303601-a6c69900-d624-11e8-8dea-9e7602e9f998.png)
I have already installed the latest version.

**Comment by EmanueleBarbalaco** [comment]
![schermata del 2018-10-22 18-06-41](https://user-images.githubusercontent.com/40856154/47303826-4552fa00-d625-11e8-846a-4b36b1ab41fd.png)

**Comment by Kidel** [comment]
You're probably using the previous version. The permission error for /opt/ has been solved in the latest release some days ago. 

Also you don't have the `check` script, so you're at least a couple of releases behind.

**Comment by Kidel** [comment]
Please make sure that you're using the latest version released and then run lwipe and install again.

**Comment by EmanueleBarbalaco** [comment]
for install latest version I have to re-follow the steps in wiki?

**Comment by lorenzo93** [comment]
There is the wiki page on [How to Update](https://github.com/KatharaFramework/Kathara/wiki/Update)

**Comment by Kidel** [comment]
I'm closing the issue. Please feel free to reply if you're having more trouble.
