### ISSUE TITLE
problem with the ping (nf_tables/iptables-legacy conflict)

### ISSUE THREAD

**Issue by mharoonj** [KatharaFramework/Kathara#215]
i am following [this](https://github.com/KatharaFramework/Kathara-Labs/blob/master/Basic%20Topics/Static%20routing/004-kathara-lab_static-routing.pdf) tutorial of kathara but the problem i am facing is that i cannot ping successfully to other ip address. It is sent but never received. I followed every step. 
I am using ubuntu :  22.04.1 LTS
kathara 3.5.5
docker : 20.10.17

I can start kathara example by 
**lstart** **command** but for the first step when we have to ping to 195.11.14.1, it says packet transmitted but 0 received.

[THIS](https://github.com/KatharaFramework/Kathara-Labs/raw/master/Basic%20Topics/Static%20routing/kathara-lab_static-routing.zip) is the sample project which i am using. it is on [this](https://github.com/KatharaFramework/Kathara-Labs/wiki/Basic-Topics) site

**Comment by tcaiazzi** [comment]
Hi @mharoonj, 

I think that your problem is related to some configuration on your host. Indeed, I just run the lab and it works fine on my Ubuntu 22.04.

![image](https://github.com/KatharaFramework/Kathara/assets/26346836/6a2a7bf8-a26c-4df5-b1b1-374cf816ad40)

Are you sure to exec the ping command on the right device (`pc1`)? 

If yes, have you any active firewall on your host?

Can you send me the output of the following command on your host?
```shell
iptables -nvL
```

**Comment by mharoonj** [comment]
@tcaiazzi I have disabled firewall on my machine 

this is screenshot of pc1
![image](https://github.com/KatharaFramework/Kathara/assets/49893886/b2963bc8-7895-432e-82c0-755cf0c46c5f)

this is screenshot of my pc terminal :
![image](https://github.com/KatharaFramework/Kathara/assets/49893886/75ed278d-629f-423a-8f53-07ed667b7353)

**Comment by tcaiazzi** [comment]
Hi  @mharoonj, 

I think the problem is related to some iptables issues on your host machine. 

It seems that you have both `iptbales-legacy` and `nf_tables`, and probably this is causing your issues. 

Try to uninstall the docker network plugin:
```shell
kathara wipe -f
docker plugin rm -f kathara/katharanp:amd64
```
Then, try to run the lab again to reinstall the plugin. 

If it does not work, can you send me the output of following command?
```shell
iptables-legacy -nvL 
```
Moreover, can you also send me a zip of the lab you are running? Just to be sure that everything is ok. 

Thanks,
Tommaso

**Comment by mharoonj** [comment]
@tcaiazzi this is how i uninstalled docker network plugin
![image](https://github.com/KatharaFramework/Kathara/assets/49893886/0959c2e4-032e-4ee4-b266-4b71d3456231)

this is the screenshot of **pc1** and the **iptables-legacy -nvL** command output
![image](https://github.com/KatharaFramework/Kathara/assets/49893886/6e38ca22-454a-4a42-94af-a0f7a3474cea)
 
and  for my pc screenshot:  
 
![image](https://github.com/KatharaFramework/Kathara/assets/49893886/65bd6215-da2d-456e-8666-7f6a9ad302de)

i am working on this file
[kathara-lab_static-routing.zip](https://github.com/KatharaFramework/Kathara/files/11487652/kathara-lab_static-routing.zip)

**Comment by tcaiazzi** [comment]
It seems that on your host the Kathara iptables rules are inserted in `nf_tables` while Docker rules are in `iptables-legacy`. 

This is how the iptables output should look like: 
![image](https://github.com/KatharaFramework/Kathara/assets/26346836/c12c7a4e-0772-46ab-913c-7af3b78d52bd)

As you can see from the screenshot, I have both the `kt-*` and the Docker rules. 

Probably, to fix the problem you need to uninstall `iptables-legacy` version and use only `nf_tables`. 

Let me know if it helps!

**Comment by mharoonj** [comment]
@tcaiazzi how to or from which command I can uninstall specifically iptables-legacy and tell system to use nf_tables only?

**Comment by tcaiazzi** [comment]
You have to specify to the OS to use `nf_tables`. To do so, you can use the following commands:
```shell
update-alternatives --set iptables /usr/sbin/iptables-nft
update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
update-alternatives --set arptables /usr/sbin/arptables-nft
update-alternatives --set ebtables /usr/sbin/ebtables-nft
```
You can find more info here: https://wiki.debian.org/nftables

Let me know if it helps!

**Comment by mharoonj** [comment]
@tcaiazzi  still not working ... it can not even ping google.com 


![image](https://github.com/KatharaFramework/Kathara/assets/49893886/0c81c979-4242-41fc-8889-87a324ffc81e)

**Comment by tcaiazzi** [comment]
@mharoonj  the network scenario is completely isolated from internet, unless you use the `--bridged` option on a device.  

So you cannot ping google from inside the lab.

Try to reboot the host after the usage of `update-alternatives`. 

Then, if the error persist, send to me the new output of `iptables`.

**Comment by mharoonj** [comment]
no success
this is new output of iptables-legacy 
![image](https://github.com/KatharaFramework/Kathara/assets/49893886/2f30ff6a-66b2-4f36-9eeb-0df32b228af3)

**Comment by tcaiazzi** [comment]
Can you also attach the output of `nf_tables` ? 

It seems that your Docker is still using `iptables-legacy` and not `nf_tables`.

**Comment by mharoonj** [comment]
@tcaiazzi  is this what you are asking about ? OR there is another command i have to type

![image](https://github.com/KatharaFramework/Kathara/assets/49893886/14133b66-e084-42e9-8967-1a6299360f38)

**Comment by tcaiazzi** [comment]
Try these steps: 
1. Uninstall Kathara.
2. Uninstall Docker.
3. Run once again these commands:
```
update-alternatives --set iptables /usr/sbin/iptables-nft
update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
update-alternatives --set arptables /usr/sbin/arptables-nft
update-alternatives --set ebtables /usr/sbin/ebtables-nft
```
4. Reboot your host.
5. Install Docker following the official guide: https://docs.docker.com/engine/install/ubuntu/
6. Install Kathara.
7. Run the lab.
8. If the problem persist, send me both the output of `iptables-legacy -nvL` and `iptables -nvL` while the lab is running.

**Comment by mharoonj** [comment]
@tcaiazzi it worked now. Thanks for your timely responses. Without you i couldnt have done this. Thanks a lot for your time and dedication.
