### ISSUE TITLE
Kathara network plugin causes docker service to be crashed (code=exited, status=2/INVALIDARGUMENT)

### ISSUE THREAD

**Issue by thanhledev** [KatharaFramework/Kathara#223]
**Describe the bug**
After upgrading the Docker engine to the latest version (24.0.2) and rebooting, Kathara emulator is not working because Docker engine could not start.

**Expected behavior**
Kathara & Docker should work as normal.

**Error log**
- Output of  command `sudo journalctl -eu docker`
`
Jun 06 21:07:18 hostname-xxx dockerd[4022]: time="2023-06-06T21:07:18.927932416+02:00" level=info msg="Starting up"
Jun 06 21:07:18 hostname-xxx dockerd[4022]: time="2023-06-06T21:07:18.928338938+02:00" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf"
Jun 06 21:07:19 hostname-xxx dockerd[4022]: time="2023-06-06T21:07:19.042941181+02:00" level=error msg="failed to enable plugin" error="failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting \"/run/xtables.lock\" to rootfs at \"/var/run/xtables.lock\": stat /run/xtables.lock: no such file or directory: unknown" id=280f350c9d6a4b2f2349d05f0974dd5610b457f60bbd7fdc5d51caa28ec86c85
Jun 06 21:07:19 hostname-xxx dockerd[4022]: time="2023-06-06T21:07:19.070171153+02:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
Jun 06 21:07:19 hostname-xxx dockerd[4022]: time="2023-06-06T21:07:19.075992287+02:00" level=info msg="Loading containers: start."
Jun 06 21:07:19 hostname-xxx dockerd[4022]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 06 21:07:19 hostname-xxx dockerd[4022]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x55c9cd19edbb]
Jun 06 21:07:19 hostname-xxx dockerd[4022]: goroutine 1 [running, locked to thread]:
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/pkg/plugins.(*Client).callWithRetry(0x0, {0xc00022b4c0, 0x1d}, {0x55c9ced04160, 0xc001658ab0}, 0x1, {0x0, 0x0, 0xc0014be828?})
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/pkg/plugins/client.go:159 +0x15b
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/pkg/plugins.(*Client).CallWithOptions(0x55c9ce2b9b01?, {0xc00022b4c0, 0x1d}, {0x0, 0x0}, {0x55c9ce8c8200, 0xc001658a80}, {0x0, 0x0, 0x0})
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/pkg/plugins/client.go:112 +0x185
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/pkg/plugins.(*Client).Call(...)
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/pkg/plugins/client.go:101
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/libnetwork/drivers/remote.(*driver).call(0xc0016606c0?, {0x55c9ce2b9b01?, 0x18?}, {0x0?, 0x0?}, {0x55c9ced051a0?, 0xc001658a80?})
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/libnetwork/drivers/remote/driver.go:135 +0xbc
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/libnetwork/drivers/remote.(*driver).getCapabilities(0xc0014be9c8?)
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/libnetwork/drivers/remote/driver.go:98 +0x52
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/libnetwork/drivers/remote.Register.func1({0xc001324090, 0x17}, 0x0)
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/libnetwork/drivers/remote/driver.go:45 +0xb6
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/libnetwork/drivers/remote.Register({0x55c9ced05240?, 0xc001668010}, {0x55c9ced29108, 0xc000576060})
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/libnetwork/drivers/remote/driver.go:65 +0x114
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/libnetwork.New({0xc0006513b0, 0x8, 0xe})
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/libnetwork/controller.go:139 +0x328
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/daemon.(*Daemon).initNetworkController(0xc0013a2000, 0xc001359290)
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/daemon/daemon_unix.go:847 +0x4e
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/daemon.(*Daemon).restore(0xc0013a2000)
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/daemon/daemon.go:505 +0x6bd
Jun 06 21:07:19 hostname-xxx systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/daemon.NewDaemon({0x55c9ced28ca8?, 0xc0000d25a0}, 0xc000d39900, 0xc000576060, 0xc00061c280)
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/daemon/daemon.go:1131 +0x2e19
Jun 06 21:07:19 hostname-xxx dockerd[4022]: main.(*DaemonCli).start(0xc000052cc0, 0xc000162000)
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/cmd/dockerd/daemon.go:232 +0xae9
Jun 06 21:07:19 hostname-xxx dockerd[4022]: main.runDaemon(...)
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/cmd/dockerd/docker_unix.go:14
Jun 06 21:07:19 hostname-xxx dockerd[4022]: main.newDaemonCommand.func1(0xc000004600?, {0xc000c55ec0?, 0x3?, 0x3?})
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:39 +0x94
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc000004600, {0xc000052090, 0x3, 0x3})
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:916 +0x862
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000004600)
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
Jun 06 21:07:19 hostname-xxx dockerd[4022]: github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(...)
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:968
Jun 06 21:07:19 hostname-xxx dockerd[4022]: main.main()
Jun 06 21:07:19 hostname-xxx dockerd[4022]:         /go/src/github.com/docker/docker/cmd/dockerd/docker.go:109 +0x18c
Jun 06 21:07:19 hostname-xxx systemd[1]: docker.service: Failed with result 'exit-code'.
Jun 06 21:07:19 hostname-xxx systemd[1]: Failed to start Docker Application Container Engine.
Jun 06 21:07:21 hostname-xxx systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
Jun 06 21:07:21 hostname-xxx systemd[1]: Stopped Docker Application Container Engine.
Jun 06 21:07:21 hostname-xxx systemd[1]: docker.service: Start request repeated too quickly.
Jun 06 21:07:21 hostname-xxx systemd[1]: docker.service: Failed with result 'exit-code'.
Jun 06 21:07:21 hostname-xxx systemd[1]: Failed to start Docker Application Container Engine.
`
**Temporary fix**
- Create an empty */var/run/xtables.lock* after logging and restart docker service.

**Comment by Skazza94** [comment]
Hi @thanhledev,
thanks for the issue.

We are already aware of such problems regarding the NetworkPlugin. 
The problem occurs when you are using a certain version of `iptables` (e.g., `legacy`) and for some reasons it is switched to another version (e.g., `nftables`).

If you check the [NetworkPlugin README](https://github.com/KatharaFramework/NetworkPlugin#troubleshooting-in-standalone-mode), you will see that there is a troubleshooting section in which we already propose the workaround that you mentioned. 

However, we are planning to switch to a NetworkPlugin that do not use Linux bridges, hence it will not require `iptables` at all.

Stay tuned for further information!

Mariano.

**Comment by fam4r** [comment]
Just to mention that the troubleshooting section has been moved here: https://github.com/KatharaFramework/NetworkPlugin/tree/90751b0bfd9448aaa440cdcf213024e516ed32a2/bridge#troubleshooting
