### ISSUE TITLE
Wrong setting of packet number to be sent

### ISSUE THREAD

**Issue by OlivierTOMATO** [KatharaFramework/Kathara#233]
Hi, I am OlivierTOMATO. Just to mention a small error.
In the send.py file, https://github.com/KatharaFramework/Kathara-Labs/blob/main/main-labs/p4/04-mpls-basics/h1/send.py
you use sendp(pkt, iface=iface, verbose=True, loop=int(sys.argv[2]), inter=0.5) to send the packets.

However, to set the number of packets sent, we should set the parameter "count" to a certain number, rather than "loop". Therefore, I guess it should be count=int(sys.argv[2])

**Comment by tcaiazzi** [comment]
Hi @OlivierTOMATO, 

Thanks for opening the issue! 

However, it is better to open issues related to labs in the [Kathara-Labs](https://github.com/KatharaFramework/Kathara-Labs) repository. 

I will close the issue here, waiting for it in the labs repository. 

Thanks for the help, 
Tommaso
