### ISSUE TITLE
Unable to create simulation scenario with Megalos

### ISSUE THREAD

**Issue by Trourest186** [KatharaFramework/Kathara#236]
Hi, I just installed a kubespray based cluster with Docker and Calico option for the installation. I've done it with step-by-step instructions according to the documentation. To be able to use Megalos I used "kathara setting" to change default manager to Megalos (Kathara I installed on master node).

 ```
NAME    STATUS   ROLES           AGE   VERSION
node1   Ready    control-plane   99m   v1.26.6
node2   Ready    <none>          98m   v1.26.6
node3   Ready    <none>          98m   v1.26.6
  ```

**My configuration files**
```
root@node1:~/lab# cat a.startup
ifconfig net0 1.1.1.1/24 up
root@node1:~/lab# cat b.startup
ifconfig net0 1.1.1.2/24 up
root@node1:~/lab# cat c.startup
ifconfig net0 1.1.1.3/24 up
root@node1:~/lab# cat lab.conf
a[0]="A"
b[0]="A"
c[0]="A"
```

**Information of devices**

- When doing a small lab build, the "CrashLoopBackOff" problem appeared in the pods. I tried to log in to the pod but can't figure out why this is happening. Looking forward to your suggestions.
![image](https://github.com/KatharaFramework/Kathara/assets/74035725/be92c7bb-ed62-4ea1-adcc-e3583e179172)

<details>

<summary>Details of a pod on which device "a" is running</summary>

![image](https://github.com/KatharaFramework/Kathara/assets/74035725/faf87d23-5e25-43e4-a725-11b4a31bfcf9)

</details>

**Comment by tcaiazzi** [comment]
Hi @Trourest186, 

Thanks for opening the issue, we are happy you are using Megalos! 

Have you installed the [Megalos CNI](https://github.com/KatharaFramework/Megalos-CNI) and the [Multus CNI](https://github.com/k8snetworkplumbingwg/multus-cni) in the cluster, before running the scenario?

You can find the installation instruction directly in the [repository](https://github.com/KatharaFramework/Megalos-CNI). 

Let me know if it helps!
Tommaso

**Comment by Trourest186** [comment]
> Hi @Trourest186,
> 
> Thanks for opening the issue, we are happy you are using Megalos!
> 
> Have you installed the [Megalos CNI](https://github.com/KatharaFramework/Megalos-CNI) and the [Multus CNI](https://github.com/k8snetworkplumbingwg/multus-cni) in the cluster, before running the scenario?
> 
> You can find the installation instruction directly in the [repository](https://github.com/KatharaFramework/Megalos-CNI).
> 
> Let me know if it helps! Tommaso

Thanks you! 
I initially installed the below yml packages then ran the lab, and it gave me the above error:
- "multus-daemonset-thick.yml" from https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/quickstart.md
- "kathara-daemonset.yml" from https://raw.githubusercontent.com/KatharaFramework/Megalos-CNI/master/kathara-daemonset.yml for Megalos-CNI

<details>

<summary>Details of components in the cluster</summary>

![image](https://github.com/KatharaFramework/Kathara/assets/74035725/899b8c84-2ae2-4c5e-a4a6-165b5545d902)


</details>
Hope you continue to help! 

Giang

**Comment by tcaiazzi** [comment]
Can you please share the output of the following command?
```
kubectl describe pod ${POD_NAME}
```

It should give us some info on what is happening!

**Comment by Trourest186** [comment]
Hi, I send you the pod information of the three devices that are failing
<details>
<summary>The pod of "a" device</summary>

![image](https://github.com/KatharaFramework/Kathara/assets/74035725/89c51f50-85d8-4768-b322-450652b9d03e)

</details>

<details>
<summary>The pod of "b" device</summary>

![image](https://github.com/KatharaFramework/Kathara/assets/74035725/6f6bb2e8-76e0-4721-b1df-9eed4c7dca6a)


</details>
<details>
<summary>The pod of "c" device</summary>

![image](https://github.com/KatharaFramework/Kathara/assets/74035725/2d8cf2b4-7e8e-46bf-817e-11da96f19c17)


</details>

**Comment by tcaiazzi** [comment]
Hi @Trourest186, 

Sorry for the delay, I was on vacation until yesterday :innocent: 

Can you please share also the output of the logs? 

```
kubectl logs ${POD_NAME}
```

Thank you for your patience!

**Comment by Trourest186** [comment]
Thanks for your patience, I have uninstalled and redone carefully on CNI so the error is fixed!
