### ISSUE TITLE
Kathara with kubernetes

### ISSUE THREAD

**Issue by Trourest186** [KatharaFramework/Kathara#237]
As I know, Kathara emulates virtual machines, network devices over containers. I'm researching to see if Kathara can be combined with K8s. For example:
- Install K8s on Kathara, because I know now there is a "kind" that is able to create k8s on the container platform
- Or is there another solution I want to install docker on Kathara containers?

Please suggest the feasibility of studying the above issues

Best regards!
Giang

**Comment by Skazza94** [comment]
Hi @Trourest186,
surely you can create a Kubernetes cluster with Kathará. 

Unfortunately, we do not have a Docker official image with Kubernetes installed. But it should be easy to create. If you manage to do so, you can open a pull request on the [Docker Images repository](https://github.com/KatharaFramework/Docker-Images).

If you need any help, feel free to reply to this issue.

Cheers,
Mariano.

**Comment by paoloPaone** [comment]
Ciao ho un problema con l'installazione di kathara dovuto  un file di configurazione JSON mancante,ho riscaricato docker e kathara ma il probela sussiste:
kathara --version
Traceback (most recent call last):
  File "/usr/lib/kathara/Kathara/setting/Setting.py", line 107, in load_from_disk
  File "/usr/lib/kathara/json/__init__.py", line 293, in load
  File "/usr/lib/kathara/json/__init__.py", line 346, in loads
  File "/usr/lib/kathara/json/decoder.py", line 337, in decode
  File "/usr/lib/kathara/json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/kathara/kathara.py", line 111, in <module>
  File "/usr/lib/kathara/Kathara/setting/Setting.py", line 109, in load_from_disk
Kathara.exceptions.SettingsError: Settings file is not valid: Not a valid JSON. Fix it or delete it before launching.

**Comment by Trourest186** [comment]
> Hi @Trourest186, surely you can create a Kubernetes cluster with Kathará.
> 
> Unfortunately, we do not have a Docker official image with Kubernetes installed. But it should be easy to create. If you manage to do so, you can open a pull request on the [Docker Images repository](https://github.com/KatharaFramework/Docker-Images).
> 
> If you need any help, feel free to reply to this issue.
> 
> Cheers, Mariano.

Thanks you so much!

**Comment by Trourest186** [comment]
Hi @Skazza94, I have read more about Kathara, so far I have two problems that even testing still does not produce results. Would you suggest me:

- I have read the issue very carefully [issuse #167](https://github.com/KatharaFramework/Kathara/issues/167), found it close to my purpose.
 Can you tell me if there is a way that when using the command "kathara lstart --privileged" the system will understand itself as "docker run -v /var/run/docker.sock:/var/run/docker.sock - v /var/run/docker.pid:/var/run/docker.pid ...". I want mount it to containers.
- Can be modified to allow Kathara to run with other runtimes such as (e.g. with sysbox-runc)?

Please take some time to support me. My knowledge is a bit limited. Thank you very much!

Best regards!
Giang

**Comment by Skazza94** [comment]
Hi @Trourest186,
see inline.

> Hi @Skazza94, I have read more about Kathara, so far I have two problems that even testing still does not produce results. Would you suggest me:
> 
> * I have read the issue very carefully [issuse #167](https://github.com/KatharaFramework/Kathara/issues/167), found it close to my purpose.
>   Can you tell me if there is a way that when using the command "kathara lstart --privileged" the system will understand itself as "docker run -v /var/run/docker.sock:/var/run/docker.sock - v /var/run/docker.pid:/var/run/docker.pid ...". I want mount it to containers.

Currently there is no way to do that, but it is something that is planned to be added (something similar is in the [`inception` branch](https://github.com/KatharaFramework/Kathara/tree/feature-inception)).

> * Can be modified to allow Kathara to run with other runtimes such as (e.g. with sysbox-runc)?

Right now, Kathará is only compatible with the Docker and Kubernetes Python APIs. We have plans to [support Podman](https://github.com/KatharaFramework/Kathara/issues/234), but in order to do so, the runtime must have a mature Python API implementation (e.g., the Podman API is still missing a TTY connection that we heavily use to connect to devices). As far as I can see, there is no Python API for sysbox-runc, so I think it is not easy to add support for it (aside from writing the API from scratch).

Hope this answers your questions!

Cheers,
Mariano.

**Comment by Trourest186** [comment]
Hi @Skazza94 

Thank you for your detailed and careful answer, thanks to which I have the answer for my direction.

Best regards!
Giang.
