### ISSUE TITLE
[macOS] lstart error when lab folder contains accented letters

### ISSUE THREAD

**Issue by Maxinho96** [KatharaFramework/Kathara#24]
I want to save a lab folder on iCloud. The general path is:
`/Users/<USER>/Library/Mobile\ Documents/com\~apple\~CloudDocs/<FOLDER>/<MAYBE A SUBFOLDER>/<MAYBE ANOTHER SUBFOLDER>/kathara-lab`

When I execute lstart I get:
`Traceback (most recent call last):
  File "/Users/Massi/Kathara/bin/python/folder_hash.py", line 28, in <module>
    print(u.generate_urlsafe_hash(lab_path))
  File "/Users/Massi/Kathara/bin/python/utils.py", line 12, in generate_urlsafe_hash
    return base64.urlsafe_b64encode(hashlib.md5(string.encode('utf-8')).digest())[:-2]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 68: ordinal not in range(128)`

Maybe the path string is too long, I don't know.

**Comment by lorenzo93** [comment]
Hi @Maxinho96,

could you check which Kathara version are you using?
You can check it by executing `$NETKIT_HOME/kathara_version`

**Comment by Maxinho96** [comment]
> Hi @Maxinho96,
> 
> could you check which Kathara version are you using?
> You can check it by executing `$NETKIT_HOME/kathara_version`

0.33.1

**Comment by lorenzo93** [comment]
Seems to be a problem with a non ascii character in your path.

Could you please tell me which character is in position 68 of your lab's path?

**Comment by Maxinho96** [comment]
> Seems to be a problem with a non ascii character in your path.
> 
> Could you please tell me which character is in position 68 of your lab's path?

It's 'à'. Can you fix this or I need to change the folder name?

**Comment by lorenzo93** [comment]
I would love to fix this issue!
The problem is that I've tried on Windows and Linux and the error is not showing.
Unfortunally I do not own a Mac.
So for now maybe is better if you remove that character from the path!

Next week I'll arrange to get one and try to fix it!

**Comment by NeejaYanglea** [comment]
Should be fixed on this branch: https://github.com/KatharaFramework/Kathara/commit/be23e309bc0800e00c3b7623ff4ede05601fe381

- [x] Test Windows 
- [x] Test Linux
- [x] Test MacOs

I've tested lstart on Windows (with Python 2.7). @lorenzo93 can you please handle the test on the other operating systems and Python versions? Some of the fixes may be depending on the OS default encoding for strings.
The issue spanned from argparse to subprocess commands.

**Comment by NeejaYanglea** [comment]
Patched some problems raised in python3. Now in Windows it works with both python 2 and 3.

**Comment by Kidel** [comment]
We also addressed a couple of bugs in the installer for this issue

**Comment by NeejaYanglea** [comment]
Fixed in the next release.
