### ISSUE TITLE
Warning: Pox supports only versions of Python: 3.6, 3.7, 3.8, 3.9

### ISSUE THREAD

**Issue by RicGobs** [KatharaFramework/Kathara#250]
### Operating System

Ubuntu 22.04

### Kathará Version

3.7.0

### Bug Description

I have created a POX component that listens and determines if packetIn events contain an IP packet. 
Using the system, I obtain an error about Pox, that supports only versions of Python: 3.6, 3.7, 3.8, 3.9.

### Steps To Reproduce

When I launch the command in the controller:
`./home/pox/pox.py IPcheck openflow.of_01 -port=6653`

I obtain:

```
POX 0.7.0 (gar) / Copyright 2011-2020 James McCauley, et al.
WARNING:version:POX requires one of the following versions of Python: 3.6 3.7 3.8 3.9
WARNING:version:You're running Python 3.11.
WARNING:version:If you run into problems, try using a supported version.
INFO:core:POX 0.7.0 (gar) is up.
```

### Expected Behavior

I have tried the controller functionalities and the system works.

The WARNING could give problems for future labs. So I have some doubts:

1. Is it possible to select a specific version of Python3 for kathara-3.7.0?

2. I have tried to use pyenv and I have set Python 3.9 as global, but it did not work. Do I need to uninstall kathara and reinstall it with the specific version of Python I want inside the containers?

3. Can this WARNING really lead to errors? if so in which specific cases?

Thanks!

### Check Command Output

```shell
Current Manager is: Docker (Kathara)
Manager version is: 24.0.7
Python version is: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
Kathara version is: 3.7.0
Operating System version is: Linux-6.2.0-37-generic-x86_64
Trying to run `Hello World` container...
Deploying devices...
Container run successfully.
Deleting devices...
```

**Comment by tcaiazzi** [comment]
Hi @RicGobs, 

Thanks for opening the issue!

The Python version of containers is not related to the one you used to install Kathara, but it depends on the Docker image you are using for the device.  The new Docker images rely on Debian12, which comes with Python3.11.

To install older versions, you can build a custom Docker image with the desired Python.  I suggest you to start from one of our official images to ensure compatibility with Kathara. 

Anyway, your scenario with Pox seems very interesting! It would be great if you share it with the community (even an example of it if this is not sharable) 😇 

https://github.com/KatharaFramework/Kathara-Labs/tree/main/community-labs

Please let me know if this helps, and do not hesitate writing to me if you encounter further problems. 

Thanks, 
Tommaso

**Comment by RicGobs** [comment]
Thanks for the reply.

Of course, I will share the scenario.

I haven't created a custom image yet, but I've tested the current kathara-3.7.0 on several POX scenarios and have never gotten any misbehavior or errors.
