### ISSUE TITLE
SDN - openvSwitch lab

### ISSUE THREAD

**Issue by FedericoYusteenappar** [KatharaFramework/Kathara#27]
Salve, sto cercando di realizzare un piccolo laboratorio SDN, ho esteso l'image di base con l'installazione del controller Ryu, ma dopo aver fatto partire openvSwitch, non c'è verso di far comunicare lo switch con il controller Ryu (che ho avviato)

**Comment by FedericoYusteenappar** [comment]
Salve, sto cercando di realizzare un piccolo laboratorio SDN, ho esteso l'image di base con l'installazione del controller Ryu, ma dopo aver fatto partire openvSwitch, non c'è verso di far comunicare lo switch con il controller Ryu (che ho avviato)

**Comment by Kidel** [comment]
The netkit_base image should already contain Ryu and OvS.

Aside from that you should describe your error (if any) or at least what you're doing in details. 
I'm not sure how to help you with the information you provided. 

I can only suggest you to give a look at this old PR from another user: https://github.com/KatharaFramework/Kathara/pull/13/commits/7eec8f6864ec1bc49c512de53794d176eb85ff99

The PR was not merged but it featured a working lab using OvS and Ryu (and, as you can see, it uses netkit_base, so there is no need to extend with other images that may or may not work). 

Good luck with your experiments :)
