### ISSUE TITLE
wrong permissions on directories of lab nodes downloading the zip

### ISSUE THREAD

**Issue by tcaiazzi** [KatharaFramework/Kathara#28]
**Describe the bug**
In LoadBalancerRandom lab when trying to use the links command on a server, it produces a '403 forbidden' error. 

**To Reproduce and Solution**
Once downloaded the LoadBalancerRandom lab in Kathara-Labs/Application Level as zip file, the permissions of server* and his sub-directories are setted on 700 rather then 754. 
Using git clone it works fine.

**Comment by Kidel** [comment]
I'm not sure this is the right place to report this. However are you using the "download as zip file" on Github or are you downloading the pre-compressed zip file from here? https://github.com/KatharaFramework/Kathara-Labs/blob/master/Application%20Level/LoadBalancerRandom/kathara-lab_loadbalancer-ws-rnd.zip

**Comment by tcaiazzi** [comment]
Sorry, probably the right place for this issue is in Kathara-labs. Anyway in both cases it doesn't work.

**Comment by Kidel** [comment]
It's fine, don't worry. 
Did you use "download as zip" from GitHub or did you download the zip file from here: https://github.com/KatharaFramework/Kathara-Labs/blob/master/Application%20Level/LoadBalancerRandom/kathara-lab_loadbalancer-ws-rnd.zip

**Comment by tcaiazzi** [comment]
I've tried both possibilities, but it doesn't work.

**Comment by Kidel** [comment]
I'm not sure if that's because of github or because of the permissions set
by the creator of the lab (also it may have been created on Windows).
I'll look into that

**Comment by Kidel** [comment]
I added a workaround in this commit: https://github.com/KatharaFramework/Kathara/commit/b3197cb6a4bb60e53c9dc08572e7259f7ef08932

Please wait for the release later today.

**Comment by Kidel** [comment]
I'm closing the issue. Please don't esitate to tell us if something still doesn't work.
