### ISSUE TITLE
Private registry support on Megalos

### ISSUE THREAD

**Issue by GioBar00** [KatharaFramework/Kathara#283]
### Feature Description

It would allow the use of images contained in private registries that one might not want to be available to the public.

To add private registry access in Kubernetes, it is required that a `kubernetes.io/dockerconfigjson` secret is created.
Furthermore an `imagePullSecrets` specification needs to be added to the pods or to a service account.

The problem is that Kubernetes secrets are namespaced so the Kubernetes secret needs to be added after the namespace is created, but before the pods are deployed. This becomes unfeasible when starting a Kathará lab.

### Solution

I have created a pull request #282 with a possible solution.

**Comment by tcaiazzi** [comment]
Hi @GioBar00, 

Thanks for the PR and the help! We really appreciate it!

We will review the changes to merge them as soon as possible. 

Ciao, 
Tommaso
