### ISSUE TITLE
Change `kathara exec` command execution behaviour to be consistent with `docker exec` and `kubectl exec`

### ISSUE THREAD

**Issue by GioBar00** [KatharaFramework/Kathara#299]
### Feature Description

The way the [kathara exec](https://www.kathara.org/man-pages/kathara-exec.1.html) behaves if different from [docker exec](https://docs.docker.com/reference/cli/docker/container/exec/) and [kubectl exec](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_exec/).
In Kathara when executing for example 
```bash
kathara exec device_name echo ciao
```
`echo` and `ciao` would be interpreted as two different commands. 

In Docker or Kubectl the `ciao` would instead be interpreted as an argument of the `echo` command and correctly printed on the screen.
I guess the behaviour in intended like this in order to be able to execute multiple commands in a virtual device with a single `kathara exec`, but I think that it would be best to be consistent with `docker` and `kubectl` and just run separate `kathara exec` commands to replicate the current behaviour.

**Comment by Skazza94** [comment]
Hi @GioBar00,
the correct way to use it is with the [double-dash separator](https://www.baeldung.com/linux/double-dash-in-shell-commands):
```
kathara exec device_name -- echo ciao
```

We converged to this version after experimenting with different styles over time, since it's the more flexible when coming to passing complex commands.

Hope this solves your problem.

Mariano.

**Comment by GioBar00** [comment]
Yes, thanks.
Then I guess is just the documentation that is not updated.

**Comment by Skazza94** [comment]
Probably yes, 
if you want, you could open a PR and update it. Would be great!

Cheers,
Mariano.

**Comment by GioBar00** [comment]
I will wait for the next release since it is about to merge and then I will look into it.
For now thanks.

Best,
Giovanni
