### ISSUE TITLE
Cannot start lab when adding new folders manually

### ISSUE THREAD

**Issue by DarthGalm** [KatharaFramework/Kathara#30]
On MacOS Mojave 10.14.1,  can't start lab when created from GUI when new folders are added manually to project (i.e. adding "var/www/html/" inside the "apache" folder)

1. Create a lab with an apache web server
2. Add folders to apache (i.e. "var/www/html/")
3. Execute "lstart" on lab
it gives the following error:
Traceback (most recent call last):
  File "/Users/myname/Kathara/bin/python/lstart.py", line 155, in <module>
    fc.win2linux_all_files_in_dir(machine_path)
  File "/Users/myname/Kathara/bin/python/file_conversion.py", line 13, in win2linux_all_files_in_dir
    win2linux(fpath)
  File "/Users/myname/Kathara/bin/python/file_conversion.py", line 7, in win2linux
    open(filename, 'wb').write(re.sub(r'\r', '', c).encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 3131: ordinal not in range(128)

Expected behavior is: Lab starting correctly

<details>
<summary>"check" Command Output</summary>

Docker version is
Docker version 18.06.1-ce, build e68fc7a

Trying to run Docker Hello World
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
d1725b59e92d: Pull complete 
Digest: sha256:0add3ace90ecb4adbf7777e9aacf18357296e799f81cabc9fde470971e499788
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

Python version is
Python 2.7.10

NETKIT_HOME is
/Users/myname/Kathara/bin

Kathara version is
/Users/myname/Kathara/bin/kathara_version

Config file contents are
unix_bin=/Users/myname/Kathara/bin/wrapper/bin/netkit_dw

Netkit temp folder contains
labs				trclgR5klR-ZZDuZuN5sCg_links
last_network_counter.txt	trclgR5klR-ZZDuZuN5sCg_machines

</details>

**Comment by Kidel** [comment]
Hi, what version of katharà are you using? 
`$NETKIT_HOME/kathara_version`
Unfortunately there is a mistake in the check script so it's not visible. 

Also please attach your lab to a reply. This may be a tricky error to fix.

**Comment by DarthGalm** [comment]
Latest version, 0.34.

Attached you'll find the lab.

Thank you.

[2015esonero.zip](https://github.com/KatharaFramework/Kathara/files/2585859/2015esonero.zip)

**Comment by Kidel** [comment]
Ok the problem is with the file `.DS_Store` (that's created automatically by macOS). It should work if you remove that. 

However it never occurred to us that you could have non-text files inside the machine folders. 
The next release will support `.DS_Store` as well as images and so on.

Meanwhile delete it manually to have your lab work.

**Comment by Kidel** [comment]
However there are a couple of errors with static routes in that lab, keep that in mind.
Specifically `router1` has the wrong interface for the default gw and `host` has itself as default gw. Fixed that and removed `.DS_Store` the lab works.

**Comment by Kidel** [comment]
Done. Will go live in release 0.34.1

**Comment by Kidel** [comment]
new release up
