### ISSUE TITLE
Unable to access to user's public_html dir

### ISSUE THREAD

**Issue by davidebersani** [KatharaFramework/Kathara#31]
In a scenario with apache2 enabled and userdir module enabled I should be able to access to user's public_html dir, for example with  `links http://open.me/~guest/`. Instead, when I try to do this, apache give me error 404. Is a problem of apache? Or is a problem of XTerm that doesn't recognize ~ in the correct way?

1. Create lab with a web server and "userdir" module enabled.
2. Put an index.html page in /home/guest/public_html on the server.
3. On a host, try `links http://<server-ip>/~guest/`
4. You should see the home putted before in the directory, instead an error 404 will appear.

Screenshot: 
![screenshot from 2018-11-15 15-57-17](https://user-images.githubusercontent.com/7922677/48560937-2fb4b580-e8ef-11e8-8e3a-91053ee67aab.png)

<details>
<summary>"check" Command Output</summary>
```
Python version is
Python 2.7.13

NETKIT_HOME is
/opt/Kathara/bin/check: line 18: ECHO: command not found

Kathara version is
/opt/Kathara/bin/kathara_version

Config file contents are
unix_bin=/opt/Kathara/bin/wrapper/bin/netkit_dw

Netkit temp folder contains
eTuSJ-_ZskNDdZF-wKHvxQ_links	 labs
eTuSJ-_ZskNDdZF-wKHvxQ_machines  last_network_counter.txt

```
</details>

**Comment by Kidel** [comment]
Hi, can you please attack the lab? There may still be permission problems from the last issue.

**Comment by davidebersani** [comment]
[lab2.zip](https://github.com/KatharaFramework/Kathara/files/2585847/lab2.zip) This is the lab.

**Comment by Kidel** [comment]
Oh, ignore my previous post. The error is probably due to the fact that you're using the `~` in the url.

**Comment by davidebersani** [comment]
Yes, I know, but I was doing an old exam that is on [http://wiki.netkit.org/index.php/Labs_Exams]( http://wiki.netkit.org/index.php/Labs_Exams ), and it required this feature.

**Comment by Kidel** [comment]
Yes but that requires the `guest` user. That's an old Netkit lab, Katharà has no `guest` user inside the `netkit_base` image, only `root`. 

We may add that feature later, but it's not supported right now.

**Comment by Kidel** [comment]
I remember doing that lab back in the day. That's an example of the Apache user module (https://httpd.apache.org/docs/2.4/howto/public_html.html). 

It probably won't be covered by the course this year. You'll probably just use links and Apache without the user module (so just the default apache folder inside `/var/www`).

I'll close the issue. Please feel free to report anything that may resemble a bug.
