### ISSUE TITLE
Kathara Python API dependency on deprecated pyuv module (Debian 12)

### ISSUE THREAD

**Issue by Pierrig1** [KatharaFramework/Kathara#311]
### Operating System

Debian12

### Kathará Version

3.7.7

### Bug Description

I am currently trying to use the Kathara Python API on a Debian 12 system, but I encountered a blocking issue due to the dependency on the pyuv module, which has been deprecated and is no longer installable.

### Steps To Reproduce

1 Set up a Debian 12 environment.
2. Create a virtual environment using python -m venv env and activate it.
3. Attempt to install pyuv with pip install pyuv.
4. The installation fails due to the module being deprecated and incompatible with the current system.

### Expected Behavior

The Kathara Python API should either avoid using deprecated libraries or suggest an alternative solution for newer systems like Debian 12.

### Check Command Output

```shell
Is there any workaround or plan to replace pyuv in future releases of Kathara?

Thank you for your help!
```

**Comment by tcaiazzi** [comment]
Dear @Pierrig1,

Thank you for opening the issue and reaching out!

The version of `pyuv` on PyPI is currently incompatible with newer versions of Python (>= 3.11). We've already addressed the issue by submitting a [PR](https://github.com/saghul/pyuv/pull/278), but unfortunately, the fix has not yet been published to PyPI by the `pyuv` maintainers.

However, as mentioned in the [Getting Started guide](https://github.com/KatharaFramework/Kathara-Labs/tree/main/tutorials/python-api/getting-started) for the API, you can still download the correct version directly from GitHub using the following command:

```
python3 -m pip install git+https://github.com/saghul/pyuv@master#egg=pyuv
```

After that, everything should work smoothly.

Please let me know if this helps, and don't hesitate to reach out if you need further assistance.

**Comment by Pierrig1** [comment]
Hello !
Thank you for your suggestion.

I tried the patch you mentioned, but unfortunately, the GitHub link for pyuv returns a 404 error, so I am unable to download the correct version. It seems the repository or branch might no longer be available.

Is there any alternative solution, or perhaps a different way to proceed?

Many thanks!

**Comment by Skazza94** [comment]
Hi @Pierrig1,
what command did you exactly run to get a 404?

I've just tried to install it from terminal and it works:
<img width="1422" alt="image" src="https://github.com/user-attachments/assets/29e58961-877e-4afa-be22-2ef01153308c">

Cheers,
Mariano.

**Comment by Pierrig1** [comment]
I initially encountered the 404 error when trying to access the address provided, but after running the command directly in the terminal, it worked perfectly. My mistake there, thanks for the clarification!
Thanks for the help !

**Comment by Skazza94** [comment]
No worries!
I am closing the issue, you can reopen it if you encounter any other problem!

Cheers,
Mariano
