### ISSUE TITLE
Kathara wipe fails on Mac M1 when no environments are active

### ISSUE THREAD

**Issue by micheleguidaa** [KatharaFramework/Kathara#313]
### Operating System

MacOS Sequoia 15.0

### Kathará Version

3.7.7

### Bug Description

When I run the kathara wipe command on a Mac with an M1 chip, and no active network environments or containers are present, the command fails with the following traceback. It appears to be related to an issue with PyInstaller handling temporary files or package resources:

### Steps To Reproduce

Open a terminal
On your Mac M1, open a terminal window.

Run kathara wipe
Execute the command kathara wipe without any active environments or containers.

Observe the error
The traceback error will appear, indicating a failure to handle the command properly when no environments are present.

### Expected Behavior

When running kathara wipe with no active environments or containers, the command should complete successfully without errors.

**Comment by tcaiazzi** [comment]
Hi @micheleguidaa, 

Thanks for opening the issue! 

We found a problem in the packaging process on macOS. However, we just released a fix that should resolve the issue. 

Try to install it: [Kathara-macos-installer-arm64-3.7.7-FIX.pkg](https://github.com/KatharaFramework/Kathara/releases/download/3.7.7/Kathara-macos-installer-arm64-3.7.7-FIX.pkg)

Please let me know if it works. 

Thanks!

**Comment by micheleguidaa** [comment]
Hi @tcaiazzi,

Thank you for the quick response and for the fix!

I just tried installing the package **Kathara-macos-installer-arm64-3.7.7-FIX.pkg**, and it works perfectly now.

Thanks again for your support!

Best,  
Michele
