### ISSUE TITLE
FRR Daemon Fails to Start in Lab Containers on Kernel >6.8 - Fedora

### ISSUE THREAD

**Issue by MarcoNapoleone** [KatharaFramework/Kathara#316]
### Operating System

Fedora Linux 40 (Workstation Edition)

### Kathará Version

3.7.7

### Bug Description

When launching a lab environment that relies on FRR, the container fails to complete the systemctl start frr command, which causes the FRR daemon to hang and prevents the generation of the frr.log file. This issue has been consistently reproduced on Fedora systems with kernel versions greater than 6.8 and across multiple Kathara versions, suggesting a possible compatibility issue between the latest kernel versions and the Docker image used.

### Steps To Reproduce

1. Launch a lab container with FRR on a Fedora system with kernel >6.8.
2. Attempt to start the FRR daemon using `systemctl start frr`
3. Observe that the command hangs, and the daemon fails to start.

e.g. using Lab "Papillon"

![image](https://github.com/user-attachments/assets/959f2056-e30c-4e7c-9dba-484fa79be522)

![Screenshot from 2024-10-30 11-25-39-redacted_dot_app](https://github.com/user-attachments/assets/2eaa4272-8e7c-4cca-8555-b6b0b7276958)

### Expected Behavior

The FRR daemon should start without issues, and a frr.log file should be generated to confirm normal operation.

### Check Command Output

```shell
user@machine:~$ kathara check
┌────────────────────────────────────────────────────────────────────┐
│                            System Check                            │
└────────────────────────────────────────────────────────────────────┘
Current Manager is:             Docker (Kathara)
Manager version is:             27.3.1
Python version is:              3.11.9 (main, Aug 15 2024, 00:00:00) 
[GCC 13.3.1 20240522 (Red Hat 13.3.1-1)]
Kathara version is:             3.7.7
Operating System version is:    Linux-6.11.3-200.fc40.x86_64-x86_64
[Deploying devices]   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/1
[Deleting devices]   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1/1
✓ Container run successfully.
user@machine:~$
```

**Comment by tcaiazzi** [comment]
Dear @MarcoNapoleone,

Thank you for reaching out and for opening the issue.

We’ve encountered this error before, and there’s a workaround available here: [KatharaFramework/Docker-Images Issue #10](https://github.com/KatharaFramework/Docker-Images/issues/10).

Unfortunately, it appears we forgot to push the necessary updates to Docker Hub. We'll address this today.

In the meantime, you can manually build the image by following these steps:

1. Clone the repository.
2. Open a terminal and navigate into the cloned directory.
3. Run the command:
    ```bash
    make frr
    ```
After that, you should be able to run the network scenarios without issues.

Let us know if this resolves the problem!

Thanks again.

**Comment by MarcoNapoleone** [comment]
Thank you so much for the quick response!

I followed your instructions, and everything is working perfectly now.

Please feel free to reach out if you need help with future RPM testing, I’d be happy to assist.
