### ISSUE TITLE
Cannot comment a single line in a configuration file

### ISSUE THREAD

**Issue by Maxinho96** [KatharaFramework/Kathara#32]
If I comment a single line in a configuration file, also the lines below it are ignored.

1. Edit a lab configuration file (I've tried with a .startup file)
2. Comment out a line which has other lines below it. e.g.:
`ifconfig eth0 30.0.0.3/24 up`
`# route add default gw 30.0.0.1 dev eth0`
`/etc/init.d/bind start`
3. Start the lab
4. Notice that the line below the comment are ignored (in the example, `/etc/init.d/bind start` is ignored)

Expected behaviour: only the commented line should be ignored

Kathará version: 0.34

<details>
<summary>"check" Command Output</summary>
```
Docker version is
Docker version 18.06.1-ce, build e68fc7a

Trying to run Docker Hello World

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/


Python version is
Python 2.7.10

NETKIT_HOME is
/Users/Massi/Kathara/bin

Kathara version is
/Users/Massi/Kathara/bin/kathara_version

Config file contents are
unix_bin=/Users/Massi/Kathara/bin/wrapper/bin/netkit_dw

Netkit temp folder contains
labs				last_network_counter.txt
```
</details>

**Comment by Kidel** [comment]
That's because of a fix for SDN that I implemented a while ago to avoid parallel comments. I'll fix it right away.

**Comment by Kidel** [comment]
Should be fixed in the next release. Meanwhile don't use comments. Thanks for submitting your issue.
