### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by Enrico204** [KatharaFramework/Kathara#39]
**Describe the bug**
Python 2 support ends on Jan 1, 2020 (see https://pythonclock.org/ ). The project should use Python 3 if it's compatible, or at least, it should suggest to use Python 3, and not Python 2, on readme files and doc.

**To Reproduce**
No steps required.

**Expected behavior**
Not applicable.

**Screenshots**
Not applicable.

**Comment by Enrico204** [comment]
I created the (draft) PR #40 for this

**Comment by Kidel** [comment]
Everything should be already compatible with Python 3

**Comment by Enrico204** [comment]
It wasn't working for me, but I'll check again :-)
However, in the README file it's still reporting Python 2.x, and I think that it would be safe to remove any Python 2 references due to the end of the support.

**Comment by Kidel** [comment]
We checked Python3 compatibility some months ago, but maybe it only worked for our environment.

I've checked your PR and it uses less implicit methods compared to what we have now. I'll test it tomorrow and probably merge.

I'll also tell the guys at the university to review the documentation.

Thank you for your contribution.

EDIT: is your version still compatible with Python 2?

**Comment by Enrico204** [comment]
I'll check the compatibility with Python 2 (actually I tested it with Python 3 only).

**Comment by Kidel** [comment]
Thank you. I'll merge it if it keeps being compatible with older systems. 

I'll also have @lorenzo93 double check if the current version works on Python3 (I think he's currently using Katharà on Python3, but maybe we should test it on a blank virtual machine).

**Comment by Enrico204** [comment]
In the mean time, I wasn't able to reproduce the original issue with Python 3 after a clean install, so that was probably something in my environment. I'll test my PR for Python 2 compatibility asap :-)

**Comment by Kidel** [comment]
If there are no errors I'd probably close this issue and discard the PR. Your branch is probably more stable on the Python 3 side, but it removes the compatibility with the current installations. 

Please feel free to open a new issue if you can reproduce the error with Python 3.
