### ISSUE TITLE
How to allow host internet access to Kathara docker node?

### ISSUE THREAD

**Issue by OlegJakushkin** [KatharaFramework/Kathara#41]
**Is your feature request related to a problem? Please describe.**
I want to have access to the internet network my node is connected to. How to do it?

**Describe the solution you'd like**
Any  that would not include manual node stop->start->new ip->manual network rerouting

At least what can be done in theory to implement or automate this?

**Comment by Kidel** [comment]
There are many ways to do it. 

In `vstart` use `--bridged`
In `lstart` use `MACHINE_NAME[bridged]=true` in your lab.conf

This will connect your `MACHINE_NAME` node to your host machine on `eth0`, giving you the possibility to access the internet. 

Another possible way is to manually create a bridged Ubuntu or Alpine container and simply link it to a Katharà node. 

Both methods require you to configure the bridged node as default gateway for external routes (or `0.0.0.0`)

**Comment by Kidel** [comment]
I'll close the issue, since there have been no replies after 7 days.
