### ISSUE TITLE
Problems with MacOs installation 

### ISSUE THREAD

**Issue by brtar96** [KatharaFramework/Kathara#42]
**Describe the bug**: No such file or directory: '/Users/Myname/Kathara/bin/../config'
Impossibility to find a file

**Expected behavior**
Should open a lab

**Screenshots**
Traceback (most recent call last):
  File "/Users/Myname/Kathara/bin/python/folder_hash.py", line 3, in <module>
    import netkit_commons as nc
  File "/Users/Myname/Kathara/bin/python/netkit_commons.py", line 44, in <module>
    kat_config = read_config()
  File "/Users/Myname/Kathara/bin/python/netkit_commons.py", line 36, in read_config
    ini = u'[dummysection]\n' + open(os.path.join(os.environ['NETKIT_HOME'], '..', 'config'), 'r').read()
IOError: [Errno 2] No such file or directory: '/Users/myName/Kathara/bin/../config'
<details>
<summary>"check" Command Output</summary>
```
Docker version is
Docker version 18.09.2, build 6247962

Trying to run Docker Hello World

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/


Python version is
Python 2.7.10

NETKIT_HOME is
/Users/myName/Kathara/bin

Kathara version is
0.34.1

Config file contents are
cat: /Users/myName/Kathara/bin/../config: No such file or directory

Netkit temp folder contains
labs
```
</details>

**Comment by Kidel** [comment]
From your check command output it seems that you lack the config file that is usually generated during the installation process. 

You should probably simply run the installer as administrator followed by `lwipe`.

Check this page: https://github.com/KatharaFramework/Kathara/wiki/Macos

**Comment by brtar96** [comment]
I've used that page to install Kathara but it doesn't help. What do you mean "followed by lwipe"?

**Comment by Kidel** [comment]
After every install or update, simply run lwipe to start clean.

What's the output of the installer? And how are you running it? For some reason the config file seems to be missing

**Comment by brtar96** [comment]
First of all, I'm using bash shell. I do -"git clone https://github.com/KatharaFramework/Kathara.git", then this: echo "export NETKIT_HOME=/Users/myName/kathara/bin" >> ~/.bash_profile and then $NETKIT_HOME/install. If I try to do sudo $NETKIT_HOME/install, it outputs $NETKIT_HOME is not set while if I run $NETKIT_HOME/install, the output is: 
Setting permissions
chflags: /Users/bruno.taricco/Kathara/bin/wrapper/bin/netkit_dw: No such file or directory
Compiling netkit_dw
Pulling images
Using default tag: latest
latest: Pulling from kathara/netkit_base
Digest: sha256:6dff40967bdca7534207fcdf920a2a328caca4b0a3140afc774739498ca4fcd8
Status: Image is up to date for kathara/netkit_base:latest
Using default tag: latest
latest: Pulling from library/alpine
Digest: sha256:b3dbf31b77fd99d9c08f780ce6f5282aba076d70a513a8be859d8d3a4d0c92b8
Status: Image is up to date for alpine:latest

**Comment by Kidel** [comment]
You don't need to use `sudo`, since the script asks you anyway. You just need to be sudo enabled (I agree that the way I istructed you was not precise, I'm sorry). 

Also please run `$NETKIT_HOME/check` again, let's see if the config file now exists. 

Also please remember to run  `$NETKIT_HOME/lwipe` just in case.

**Comment by brtar96** [comment]
Docker version is
Docker version 18.09.2, build 6247962

Trying to run Docker Hello World

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/


Python version is
Python 2.7.10

NETKIT_HOME is
/Users/myName/kathara/bin

Kathara version is
0.34.1

Config file contents are
unix_bin=/Users/myName/kathara/bin/wrapper/bin/netkit_dw

Netkit temp folder contains
ls: /Users/myName/netkit_temp/: No such file or directory

**Comment by Kidel** [comment]
It seems that we got past the generation of the config file. Try running commands now. It should work.

**Comment by brtar96** [comment]
It seems working. Thank you.
