### ISSUE TITLE
Connect Lab to Internet

### ISSUE THREAD

**Issue by edge33** [KatharaFramework/Kathara#51]
Is there a way in Kathara to access Internet from the Lab, in a similar fashion to the way we are used to in Netkit?

What I usually do in netkit is to set a tap interface on the host machine and route all the traffic going to the lab to the first node of the lab itself.

**Comment by Kidel** [comment]
You can use the `bridged` option in `vstart` or in `lab.conf` (eg: `pc1[bridged]=true`), as stated in the **Manual** section of the readme. This will add an an interface that connects to the host machine.
