### ISSUE TITLE
lstart for only one virtual machine

### ISSUE THREAD

**Issue by nhvlong** [KatharaFramework/Kathara#53]
Hello everyone, 

I have a question about the starting a virtual machine with Kathará.

The question is: How can I use the lstart command to start only 1 machine instead of all of the machine I declared.
Example: I created the folder named TestLab. In this folder, there are 2 subfolder named PC1 and PC2. Moreover, I had the .startup files for them. But, I cannot use lstart PC2 as I used before in Netkit to start only PC2.

Please help me and thanks a lot.

**Comment by Kidel** [comment]
You can either use vstart or start a lab with 2 nodes to later delete.one

**Comment by nhvlong** [comment]
Sorry, maybe my question is not clear. What I wanted is to start one or two or more specified nodes instead of all of them. For example: I had 10 nodes (from node 1 to 10) in my lab, but I want to start only node 2 and node 3 in this lab (to test them firstly). How can I do that in Kathará? Because in Netkit, I can easily do that by using _lstart node2 node3_

**Comment by Kidel** [comment]
You can do something similar with 1 node only (lstart node1)

**Comment by nhvlong** [comment]
Here is the result when I tried to start only the PC1 instead of starting all of the nodes in my lab.
![Screen Shot 2019-07-10 at 10 30 14](https://user-images.githubusercontent.com/9139943/60938355-dece5300-a2fd-11e9-9cec-159d0f20ce39.png)

**Comment by Kidel** [comment]
It may be a bug with the current version. Please provide the version you're using and the contents of your lab

**Comment by nhvlong** [comment]
I think I got the answer myself. Because I named my node with a or several Capitalize Letter(s), Kathará won't start successfully. For example, I named my node is **PC3** with 'P' and 'C' are Capitalize Letters. Hence, I got the bug "Please specify at least a machine". When I change my node's name to **pc3** with no capitalize letter, everything is going well.

Could you please show me how to modify the python code in Kathará to pass over this bug and allow the Capitalize Letter in node's name??

**Comment by Kidel** [comment]
Unfortunately Docker only allows lowercase names for containers, so that's working as intended.
