### ISSUE TITLE
vstart not working properly

### ISSUE THREAD

**Issue by anemos-sf** [KatharaFramework/Kathara#56]
Typing the command (from Kathara Manual])

vstart --eth 0:A --eth 1:B pc1

actually creates a new VM only with one (eth0) network interfaces

Both eth0 and eth1 were expected to be created.

[check.txt](https://github.com/KatharaFramework/Kathara/files/3546107/check.txt)

**Comment by anemos-sf** [comment]
> Typing the command (from Kathara Manual])
> 
> vstart --eth 0:A --eth 1:B pc1
> 
> actually creates a new VM only with one (eth0) network interfaces
> 
> Both eth0 and eth1 were expected to be created.
> 
> [check.txt](https://github.com/KatharaFramework/Kathara/files/3546107/check.txt)

Solved: the following command creates a VM with three net interfaces (A, B and C)

vstart --eth 0:A 1:B 2:C pc99

**Comment by Kidel** [comment]
Yes, I was about to tell you that `--eth` takes a list. I'll make sure to add an example in the manual, thank you.
