### ISSUE TITLE
Different interface name connection fails?

### ISSUE THREAD

**Issue by mostafaei** [KatharaFramework/Kathara#57]
Hi all,

I am creating a simple interdomain topology with two border routers. The framework cannot connect two interfaces of two border routers (C-----eth1--R2--eth0--------B--------eth1--R1--eth0--------A).  I cannot ping from eth0 of R2 to eth1 of R1. Am I doing something wrong?

Here is the script generated by Kathara lab generator;
#! /bin/sh
# Remember to use 'chmod +x' (o 'chmod 500') on the .sh file. The script will self-destruct

rm -rf "$(dirname "$0")/lab"
mkdir "$(dirname "$0")/lab"
cd "$(dirname "$0")/lab"

mkdir -p router1
mkdir -p router2
mkdir -p router1/etc/zebra
mkdir -p router2/etc/zebra
touch lab.conf
echo 'router1[0]=A' >> lab.conf
echo 'router1[1]=B' >> lab.conf
echo 'router2[0]=B' >> lab.conf
echo 'router2[1]=C' >> lab.conf
touch router1.startup
echo 'ifconfig eth0 10.0.0.1/24 up' >> router1.startup
echo 'ifconfig eth1 10.0.0.2/24 up' >> router1.startup
echo '/etc/init.d/zebra start' >> router1.startup
touch router2.startup
echo 'ifconfig eth0 10.0.0.3/24 up' >> router2.startup
echo 'ifconfig eth1 20.0.0.1/24 up' >> router2.startup
echo '/etc/init.d/zebra start' >> router2.startup
touch router1/etc/zebra/daemons
echo 'zebra=yes' >> router1/etc/zebra/daemons
echo 'bgpd=yes' >> router1/etc/zebra/daemons
touch router1/etc/zebra/zebra.conf
echo 'hostname zebra' >> router1/etc/zebra/zebra.conf
echo 'password zebra' >> router1/etc/zebra/zebra.conf
echo 'enable password zebra' >> router1/etc/zebra/zebra.conf
echo 'log file /var/log/zebra/zebra.log' >> router1/etc/zebra/zebra.conf
touch router1/etc/zebra/bgpd.conf
echo 'hostname bgpd' >> router1/etc/zebra/bgpd.conf
echo 'password zebra' >> router1/etc/zebra/bgpd.conf
echo 'enable password zebra' >> router1/etc/zebra/bgpd.conf
echo 'router bgp 1' >> router1/etc/zebra/bgpd.conf
echo 'network 10.0.0.0/24' >> router1/etc/zebra/bgpd.conf
echo 'neighbor 10.0.0.3 remote-as 2' >> router1/etc/zebra/bgpd.conf
echo 'log file /var/log/zebra/bgpd.log' >> router1/etc/zebra/bgpd.conf
echo 'debug bgp' >> router1/etc/zebra/bgpd.conf
echo 'debug bgp events' >> router1/etc/zebra/bgpd.conf
echo 'debug bgp filters' >> router1/etc/zebra/bgpd.conf
echo 'debug bgp fsm' >> router1/etc/zebra/bgpd.conf
echo 'debug bgp keepalives' >> router1/etc/zebra/bgpd.conf
echo 'debug bgp updates' >> router1/etc/zebra/bgpd.conf
touch router2/etc/zebra/daemons
echo 'zebra=yes' >> router2/etc/zebra/daemons
echo 'bgpd=yes' >> router2/etc/zebra/daemons
touch router2/etc/zebra/zebra.conf
echo 'hostname zebra' >> router2/etc/zebra/zebra.conf
echo 'password zebra' >> router2/etc/zebra/zebra.conf
echo 'enable password zebra' >> router2/etc/zebra/zebra.conf
echo 'log file /var/log/zebra/zebra.log' >> router2/etc/zebra/zebra.conf
touch router2/etc/zebra/bgpd.conf
echo 'hostname bgpd' >> router2/etc/zebra/bgpd.conf
echo 'password zebra' >> router2/etc/zebra/bgpd.conf
echo 'enable password zebra' >> router2/etc/zebra/bgpd.conf
echo 'router bgp 2' >> router2/etc/zebra/bgpd.conf
echo 'network 20.0.0.0/24' >> router2/etc/zebra/bgpd.conf
echo 'neighbor 10.0.0.2 remote-as 1' >> router2/etc/zebra/bgpd.conf
echo 'log file /var/log/zebra/bgpd.log' >> router2/etc/zebra/bgpd.conf
echo 'debug bgp' >> router2/etc/zebra/bgpd.conf
echo 'debug bgp events' >> router2/etc/zebra/bgpd.conf
echo 'debug bgp filters' >> router2/etc/zebra/bgpd.conf
echo 'debug bgp fsm' >> router2/etc/zebra/bgpd.conf
echo 'debug bgp keepalives' >> router2/etc/zebra/bgpd.conf
echo 'debug bgp updates' >> router2/etc/zebra/bgpd.conf
rm "../$0"

Ciao,
Habib

**Comment by lorenzo93** [comment]
Hi,

I think you just mispelled the IP addresses of the interfaces.
A router needs to separate two different subnets but you place router1 with both the interfaces on the same subnet (10.0.0.0/24).
In your figure you have three collision domains (A, B, C) so you'll need to assign a different subnet for each of them to work correctly.

**Comment by mostafaei** [comment]
thanks. ;)
