### ISSUE TITLE
Assign a dedicated cpu core to each container

### ISSUE THREAD

**Issue by mostafaei** [KatharaFramework/Kathara#60]
I need to assign a dedicated number of cores to each container in the network topology due to the performance issues. I know that it is possible to assign a dedicated amount of memory to each container but not sure about the number of cores. Looking at docker documentation I found this:
https://docs.docker.com/config/containers/resource_constraints/

which for example says "If you have 1 CPU, each of the following commands guarantees the container at most 50% of the CPU every second.
**Docker 1.13 and higher:**
docker run -it --cpus=".5" ubuntu /bin/bash
**Docker 1.12 and lower:**
$ docker run -it --cpu-period=100000 --cpu-quota=50000 ubuntu /bin/bash
"
Any chance to do that?

**Comment by Kidel** [comment]
It's certainly possible with docker commands, but those were not in the initial netkit interface, so they were not implemented in Katharà. Maybe @lorenzo93 can add them in the new version that's going to be released next week, or push them in a later update.

**Comment by mostafaei** [comment]
thanks for the update!!!

**Comment by lorenzo93** [comment]
Hi,
we published the new version of Katharà.
It is now possible to specify the cpus assigned to each machine.

You can specify this either using `kathara vstart --cpus 0.5 -n machineName` or putting a line like this in your lab.conf file:
```
machineName[cpus]=0.5
```

For further documentation please refer to the "Manual" section of the wiki

**Comment by mostafaei** [comment]
Thanks for the notification!
