### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by notprime** [KatharaFramework/Kathara#63]
I get this error when I launch kathara.
I have windows education and followed everything reported on the installation guide.
I also tried doing a kathara check but I get the same error
![kathara](https://user-images.githubusercontent.com/42040779/68338640-3da4ad00-00e3-11ea-8c4a-6ca8a3ae67d2.png)

**Comment by aliceinland** [comment]
I have the same issue with macOS and I also followed the guide step-by-step. 
Did you fix the problem?

**Comment by Skazza94** [comment]
Hello, we're addressing this issue right now. A fix will be released in the next hours.

**Comment by notprime** [comment]
Thank you! I just thought it was a problem of mine, cos I had zero problem installing and running everything on my laptop, problem arised on my computer.

**Comment by Skazza94** [comment]
Hi,
a new version of Kathará has been released (v. **2.0.9**). This will fix the issue. 

Sorry for the inconvenience and thanks for pointing out the bug.
