### ISSUE TITLE
Compiling for non debian Linux distributions

### ISSUE THREAD

**Issue by S3ntinelX** [KatharaFramework/Kathara#64]
Is there any way to compile Kathara on Linux distributions which are not based on debian specifically Arch.

**Comment by Skazza94** [comment]
Hi, unfortunately we're currently only supporting Debian-based OSes.

However, if you know how to build an Arch package you can still do it on your own. You can replicate how we build/pack our .deb file, scripted [here](https://github.com/KatharaFramework/Kathara/tree/master/scripts/Linux/debian).

If you're able to build an arch package, please make a pull request with the scripts.

Thanks,
Mariano.

**Comment by Skazza94** [comment]
Since the last reply was 11 days ago I'm considering the issue as solved or no longer relevant.
