### ISSUE TITLE
How to create a symmetric NAT

### ISSUE THREAD

**Issue by chanduthedev** [KatharaFramework/Kathara#67]
Hi Kathara team,

Thank you for such a nice tool. 
I would like to know the documentation or steps to create symmetric NAT.
I can able to create router, but could not able to create NAT.

My apologies if it is basic question.

Thanks in advance.

**Comment by Skazza94** [comment]
Hi @chanduthedev,
you can build a symmetric NAT using `iptables` rules.

You can place those rules into the machine startup files, so they'll be run at the machine creation. You can find those commands with a quick [Google search](https://www.google.com/search?client=firefox-b-e&q=symmetric+nat+iptables).
