### ISSUE TITLE
How to communicate between host machine and virtual pc1?

### ISSUE THREAD

**Issue by chanduthedev** [KatharaFramework/Kathara#68]
Hi Team,

I have created a one virtual pc1 as shown in the below pic. My use case is one application is running on pc1 and I would like to access that application on host machine. How to communicate between host machine and pc1.  Please help on this.

<img width="250" alt="Screenshot 2019-12-09" src="https://user-images.githubusercontent.com/6205951/70400082-c5276800-1a63-11ea-87b1-5da69460e201.png">

Thanks

**Comment by chanduthedev** [comment]
Is it possible to access a application running in virtual pc1 from host machine using browser? if possible please let me know the steps/settings to access in the browser from host machine.

Thanks

**Comment by Skazza94** [comment]
Hello,
to bridge the application from the container to the host, you can add the `port` option to `pc1` in the `lab.conf` file. Read the man pages for a more detailed explanation [here](https://www.kathara.org/man-pages/kathara-lab.conf.5.html).

**Comment by chanduthedev** [comment]
@Skazzino thank you for the reply.
As per the man page I edited the lan.conf from existing lab [kathara_lab_arp](https://github.com/KatharaFramework/Kathara-Labs/tree/master/Basic%20Topics/ARP) as below.

**Comment by chanduthedev** [comment]
@Skazzino thank you for the reply.
As per the man page I edited the lan.conf from existing lab [kathara_lab_arp](https://github.com/KatharaFramework/Kathara-Labs/tree/master/Basic%20Topics/ARP) as below.

lab.conf:
-----
r1[0]="A"
r1[1]="B"

r2[0]="C"
r2[1]="B"

pc1[0]="A"
pc1[bridged]=true
pc1[port]=8088

pc2[0]="C"

pc3[0]="C"



pc1.startup:
---
ifconfig eth0 195.11.14.5 up
#route add default gw 195.11.14.1
route add default gw 0.0.0.0

I can able to create a lab successfully with above changes. and installed my application  running at port 8088 on pc1. But I am unable to access from host machine. Can you please help me on this. (I can able to ping from pc1 -> host)

I am doing this on my Mac OS X.

Thanks

**Comment by Skazza94** [comment]
Hi @chanduthedev,
the application in `pc1` should run on port 3000. As described in man pages, when you use the `port` option, the port 3000 of the container will be bound to the port specified in the option.

In this case, port 3000 will be bound to port 8088 on the host.

**Comment by chanduthedev** [comment]
It was working fine. I can able to access pc1 from host machine. Thanks for the help.

I am setting lab from [kathara_lab_arp](https://github.com/KatharaFramework/Kathara-Labs/tree/master/Basic%20Topics/ARP)  structure like below and  I want to pass the data to pc2 from host machine via pc1.

<img width="200" alt="image" src="https://user-images.githubusercontent.com/6205951/70702861-f45f0300-1d09-11ea-9ad3-7bbf77416822.png">

pc1.startup:
----
ifconfig eth0 195.11.14.5 up
#route add default gw 195.11.14.1
route add default gw 0.0.0.0     <-------

I added default gateway as 0.0.0.0 to access host. At the same time I want to send data to pc2, but gate way at pc1 is for host only. <br>**Is it possible to configure another gateway to send data to pc2 via r1?** <br>

**Comment by chanduthedev** [comment]
Thanks for the help. Below configuration in pc1.startup file worked.

pc1.startup:
---------
ifconfig eth0 195.11.14.5 up
route add default gw 195.11.14.1
route add -net 172.17.0.0/16 gw 0.0.0.0
