### ISSUE TITLE
How to install kathara on centOS 8?

### ISSUE THREAD

**Issue by chanduthedev** [KatharaFramework/Kathara#70]
Hi Team,

Can you please let me know how to install Kathara on centOS 8? I referred [this](https://github.com/KatharaFramework/Kathara/wiki/Linux) from documentation, but could not able to find installation steps for centOS from that link. Please help on this.

Thanks

**Comment by Skazza94** [comment]
Hi, as already explained in #64, we're currently only supporting Debian-based OSes.

However, if you know how to build a CentOS package you can still do it on your own. You can replicate how we build/pack our .deb file, scripted [here](https://github.com/KatharaFramework/Kathara/tree/master/scripts/Linux/debian).

If you're able to build a CentOS package, please make a pull request with the scripts.

**Comment by chanduthedev** [comment]
Thank you for the response.
