### ISSUE TITLE
 traffic analysis

### ISSUE THREAD

**Issue by Sunsapience** [KatharaFramework/Kathara#72]
I'm interested in kathara, it's a great simulation tool. I now try to use it to simulate a routing network for network traffic analysis. However, currently only ping mode can be used. The amount of this traffic is too small to meet the requirements. Do you have a better way? Many thanks.

**Comment by Kidel** [comment]
Hi, thanks for being interested in Katharà.
You can use the current system to add any script to a network node and run a startup command to start it. 
What you need is the [lstart](https://www.kathara.org/man-pages/kathara-lstart.1.html) command in a [lab directory](https://www.kathara.org/man-pages/kathara-lab-dirs.7.html) containing your node folders (with any script you want) and the [lab.conf file](https://www.kathara.org/man-pages/kathara-lab.conf.5.html).

**Comment by Sunsapience** [comment]
Thank you very much for your reply.
I try to write a Python script (send packets using the scapy module) in the node directory, and then run the Python file in the node's startup file. But the node's xterm says: ImportError: No module named 'scapy'. I guess it may be that the module is not in the docker images, and I may need to regenerate the images.
So, do you have a better suggestion for the above question, or a traffic generation tool?
Thank you very much.

**Comment by lorenzo93** [comment]
Hi,

You just need to install scapy in the node.
Before running your python script, in the startup file, just run a `pip install scapy` to install scapy.
If you have other dependencies it would be better to install them from a `requirements.txt` file just like you would do in your machine

**Comment by Sunsapience** [comment]
My initial thought was this. I want to do "pip install XX" operation in the node's xterm. However, there is no pip command. I tried "apt-get install python-pip (python3-pip)" with no success, which may be the cause of the network. I am using the intranet, so I should find their offline installation packages. But this has another problem, how do I send the installation package to the node.
I'm not sure if there is something wrong with my thinking.
By the way, I think these operations may not be saved when I start emulating the network again.
Thanks again for your reply.

**Comment by Kidel** [comment]
You need to specify startup operations in the startup file of your node. E.g. your node is called 'foo' and you have a 'foo.startup' file in your lab folder.

Also in order to use apt or pip you need to have that node bridged (`foo[bridged]=true` in your lab.conf if I recall correctly, check the manual), otherwise the node is isolated from the internet and you can't download anything.

Another way (but I don't suggest it for this simple task) is to create your own docker image from the base kathara one and you specify your custom image using the `image` option in lab.conf.

**Comment by Sunsapience** [comment]
Thank you very much for your suggestion, it helped me a lot. This issue has now been resolved.
Thanks to you and your team.
