### ISSUE TITLE
interface and convenience

### ISSUE THREAD

**Issue by Ellie-fans** [KatharaFramework/Kathara#74]
Hello.
I am using kathara and it is a nice tool.
There are two issues that bother me now, and I want to discuss them with you.
One is that I need to write multiple configuration files each time. Is there any more convenient operation to avoid these operations. For example, I want to build an upper-level interface, and run it through the interface instead of the configuration file.
The other is how I can output the results to my host. For example, I want to output the obtained routing information to an external host. I haven't figured out how to achieve this.
Do you have any suggestions for these?
Looking forward to your reply.

**Comment by Skazza94** [comment]
Hi @c21594 and thanks for using Kathara.

About the first question, I don't understand what you want to obtain.
About the second one, it is possible to share files/folder with from the container to the host putting them into the container's `/shared` folder.

**Comment by Skazza94** [comment]
Since the last reply was 8 days ago I'm considering the issue as solved or no longer relevant.

If you need further support, you can open another issue.

Thanks!
