### ISSUE TITLE
Critical error when .deb files in device directory

### ISSUE THREAD

**Issue by vitome** [KatharaFramework/Kathara#83]
**Describe the bug**
I just want to install some .deb packets at startup, copying them in the directory of a device. However, I receive this error: CRITICAL - object of type 'NoneType' has no len()
In the specific, I want to install udpchd, then I copied the files busybox_1%3a1.22.0-19+b3_amd64.deb  udhcpd_1%3a1.22.0-19+b3_amd64.deb
in my pc1 directory

**To Reproduce**
1. Create a very simple lab.conf with only one machine
2. Copy the two files (acquired using apt install -d udhcpd) in the machine
3. kathara lstart

**Expected behavior**
The machine installs the packages and runs with it.

**Screenshots**

<details>
<summary>"check" Command Output</summary>
*	Current Manager is: Docker (Kathara)
*	Manager version is: 18.09.7
*	Python version is: 3.6.9 (default, Nov  7 2019, 10:44:02) - [GCC 8.3.0]
*	Kathara version is: 2.2.1
*	Trying to run `Hello World` container...
Deploying links...
Deploying machines... |################################| 1/1
*	Container run successfully.
Deleting machines... |################################| 1/1
Deleting links...

</details>

**Comment by Skazza94** [comment]
Hi. As a friendly reminder, the bugfix for this issue has been included in the latest Kathara release (v2.2.2).
