### ISSUE TITLE
Question : About /shared and /hostname directories

### ISSUE THREAD

**Issue by CedricDly** [KatharaFramework/Kathara#86]
Hi,

I don't understand how the kathara settings number 4 and 5 work. When launching a new lab with default settings, I can access the /shared and /hostname folders. I thought that if I was disabling the "automatic mount" option, these folders would disappear from the virtual machines, or at least be unaccessible, but I still can access them when these options are desactivated (I checked the ~/.conf/kathara.conf JSON just to be sure).
So I am afraid I did not understand the purpose of these options, or how it works.

Thanks in advance. Regards

**Comment by Skazza94** [comment]
Hi @CedricDly,
the correct behavior is that disabling `/shared` or `/hosthome` folder, it is displayed in the container but not bound to any volume (so it is empty).

However, there was a bug that was causing the reported behavior (`/shared` and `/hosthome` mounted even when disabled) and it has been fixed and will be included in the next Kathara release.

Thanks for reporting the bug and sorry for the inconvenience.
