### ISSUE TITLE
vstart missed --privileged flags in source.

### ISSUE THREAD

**Issue by thanhledev** [KatharaFramework/Kathara#88]
It seems that the vstart command of kathara missed the privileged args in the code.

***Steps to reproduce the behavior:***
1. I have created a custom docker image for vyos at thanhledev/vyos:0.0.3. It works when using these following commands:
- docker run -d --name vyatta --privileged thanhledev/vyos:0.0.3
- docker exec -it vyatta /bin/vbash
I can see the configuration pre-installed by using: "show configuration" and be able to login to vyos (default cred: vyos/vyos).
Check the docker container:
- docker inspect vyatta  | grep -i privileged 
give us the result: "Privileged": true.
2. However, when using the same docker image with kathara:
- sudo kathara vstart -n vyatta-kathara -i thanhledev/vyos:0.0.3 --eth 0:A 1:B --privileged 
I cannot login to vyos since the configuration file is missing.
Check the docker container:
- docker inspect kathara_thanhle_vyatta_<random_uuid>  | grep -i privileged 
give us the result: "Privileged": false

**Expected behavior**
If you compare the code of src/Resources/command/LstartCommand.py - line 201:
ManagerProxy.get_instance().deploy_lab(lab, privileged_mode=args.privileged)

and src/Resources/command/VstartCommand.py  - line 193:
ManagerProxy.get_instance().deploy_lab(lab)

I checked the associated functions in src/Resources/manager/docker/DockerMachine.py and everything seems fine.

Please kindly check this weird issue. Thanks a lot.

Best regards,
Thanh Le.

**Comment by Skazza94** [comment]
Hi @thanhledev,
thanks for pointing out the issue. We already noticed that there's a problem in the code and we'll fix it as soon as possible!

Thanks.

**Comment by lorenzo93** [comment]
Hi @thanhledev,

we fixed the bug and released a new version (2.2.3). If you are on Windows or MacOS you can already download the new release, if you are on linux will be available in a couple of hours (launchpad times to build and deploy a package).
