### ISSUE TITLE
Installation on Ubuntu 20.04 - Focal

### ISSUE THREAD

**Issue by whatever4711** [KatharaFramework/Kathara#89]
**Describe the bug**
Try to install Katharà with `apt` results in an unmet dependency

**To Reproduce**
1. Install a clean Ubuntu 20.04 system
2. Install docker with `apt install docker.io`
3. Add Katharà to the keyring `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 21805A48E6CBBA6B991ABE76646193862B759810`
4. Add repository `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 21805A48E6CBBA6B991ABE76646193862B759810`
5. Try to install Katharà `apt update && apt install kathara`

**Expected behavior**
An installation of Kathará with working dependencies

**Missing Library**
```
The following packages have unmet dependencies:
 kathara : Depends: libffi6 (>= 3.0.4) but it is not installable
E: Unable to correct problems, you have held broken packages
```
P.S.:
Ubuntu 20.04 comes with `libffi7`, which might cause the installation issue.

**Comment by Skazza94** [comment]
Hi @whatever4711,
thanks for the issue.

We're still compiling Kathará on Ubuntu Eoan (19.10) so we never checked the compatibility with 20.04 and beyond. However, after this issue we'll proceed to fix it as soon as possible.

Mariano.

**Comment by Skazza94** [comment]
Hi @whatever4711,
we uploaded a new version of Kathará (2.2.5) on Launchpad which is compatible with Ubuntu Focal.

Thank you for reporting the problem. I'll close the issue.
