### ISSUE TITLE
SDN Not working - Kathara installed 02MAY2020 - Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by saxsoares** [KatharaFramework/Kathara#91]
Hi,

I just installed Kathara using apt but the virtual machines can't find ovs-vsctl or ryu-manager commands. I also rememeber that some time ago (long time), in an old Ubuntu version, I got OpenVswitch working. 

What I have to do for get SDN tools working?

**Comment by saxsoares** [comment]
I found out that Kathara/quagga was my default image. So I use 'kathara settings' to change to kathara /sdn image. This solve my problem, but you say in another issue that the base image was able to run SDN tools. 

Sorry for my bad english.

**Comment by lorenzo93** [comment]
Hi @saxsoares ,

I'm sorry for the old issue, last October we released a new version of Kathará that was completely re-written and for that purpose we built also dedicated images (in previous version the image name was hard-coded into Kathará) to have a minor impact on disk usage.

What you achieved  is correct, to run SDN you need to switch the default image to `kathara/sdn`. Remember also that you can select a specific docker image for each device in your lab using the `lab.conf` file.

As an example:
```
deviceName[image]=kathara/quagga
sdnSwitchName[image]=kathara/sdn
```
