### ISSUE TITLE
Custom Images not working properly

### ISSUE THREAD

**Issue by saxsoares** [KatharaFramework/Kathara#94]
**Describe the bug**
I did the steps to extends Kathará Images (https://github.com/KatharaFramework/Docker-Images). I could installl packages without problem. But theses packages don't work after installation (inside a vm, or even when docker connected by docker exec ..... bash.

I can create new files when I edit the images, and these files will exists inside vm machines that uses the changed image. But packages installed didn't work.

**To Reproduce**
1. Do the steps from here :https://github.com/KatharaFramework/Docker-Images to extends kathara/sdn image.
2. Install any package you want. I tried quagga package and cowsay package to test. The installation works fine.
3. Run a Lab or just a vm with those image. 
4. Try to run theses packages

**Comment by tcaiazzi** [comment]
Hi @saxsoares , 
sorry for the delay! 
I tried to reproduce your issue and I noticed that some packages like "bb" and "cowsay" are installed inside the /usr/games directory. This behaviour is inherited from debian 9 on which our images are based. 
To overcome this, when you install a package, try to run it. If the system does not found it, use `dpkg -L <package-name>`, to know where it is installed. Then add this directory to the PATH variable. 
However, this is needed only for packages not located in `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin` (which is the default path). 

Thanks, 
Tommaso
